services:
  postgres:
    image: postgres:16-alpine
    container_name: runway-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresdev
      POSTGRES_DB: runway_finance
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  next16-app:
    container_name: runway-app
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3001:3000"
    environment:
      - NEXTAUTH_URL=http://10.1.1.10:3001
      - NEXTAUTH_SECRET=super-secret-key-for-dev-only-change-in-production
      - GOOGLE_CLIENT_ID=172398384702-vu31bbe5ojj8sdmppagk0quf4bl7ipa9.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=YOUR_GOOGLE_CLIENT_SECRET
      #- NODE_ENV=production
      - NEXTAUTH_TRUST_HOST=true
      - DATABASE_URL=postgresql://postgres:postgresdev@postgres:5432/runway_finance
      - SYNC_CRON_SCHEDULE=0 */6 * * *
      - ENCRYPTION_KEY=15c164990b3bcfd12b7e734fada058bf9e6fbeb25583e1f5972e80e72eec5685 ##must be 64 char hex
      - REGISTRATION_PIN=05091987
    depends_on:
      - postgres
    command: ["node", "server.js"]

volumes:
  pgdata:
