services:
  next16-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3001:3000"
    environment:
      - NEXTAUTH_URL=http://10.1.1.10:3001
      - NEXTAUTH_SECRET=super-secret-key-for-dev-only-change-in-production
      - GOOGLE_CLIENT_ID=172398384702-vu31bbe5ojj8sdmppagk0quf4bl7ipa9.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=YOUR_GOOGLE_CLIENT_SECRET
      - NODE_ENV=production
      - NEXTAUTH_TRUST_HOST=true
      - DEBUG=true
    command: ["node", "server.js"]
