import { auth } from 'auth';
import { getDb } from '@/lib/db';
import { paystubs, paystubLineItems, transactions } from '@/lib/db/schema';
import { eq, and } from 'drizzle-orm';
import { invalidateUserSearchCache } from '@/lib/services/search-cache';

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  const dataUserId = session?.user ? ((session.user as any).dataUserId ?? session.user.id) : undefined;
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const { id } = await params;

  const [paystub] = await db
    .select()
    .from(paystubs)
    .where(and(eq(paystubs.id, id), eq(paystubs.userId, dataUserId)))
    .limit(1);

  if (!paystub) {
    return Response.json({ error: 'Paystub not found' }, { status: 404 });
  }

  const lineItems = await db
    .select()
    .from(paystubLineItems)
    .where(eq(paystubLineItems.paystubId, id));

  return Response.json({ ...paystub, lineItems });
}

export async function PATCH(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  const dataUserId = session?.user ? ((session.user as any).dataUserId ?? session.user.id) : undefined;
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const { id } = await params;

  // Verify ownership
  const [existing] = await db
    .select()
    .from(paystubs)
    .where(and(eq(paystubs.id, id), eq(paystubs.userId, dataUserId)))
    .limit(1);

  if (!existing) {
    return Response.json({ error: 'Paystub not found' }, { status: 404 });
  }

  let body: Record<string, any>;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: 'Invalid request body' }, { status: 400 });
  }

  const updates: Record<string, any> = {};
  if (body.employerName !== undefined) updates.employerName = body.employerName;
  if (body.employeeName !== undefined) updates.employeeName = body.employeeName;
  if (body.payPeriodStart !== undefined) updates.payPeriodStart = body.payPeriodStart;
  if (body.payPeriodEnd !== undefined) updates.payPeriodEnd = body.payPeriodEnd;
  if (body.checkDate !== undefined) updates.checkDate = body.checkDate;
  if (body.adviceNumber !== undefined) updates.adviceNumber = body.adviceNumber;
  if (body.grossCurrent !== undefined) updates.grossCurrent = String(body.grossCurrent);
  if (body.taxesCurrent !== undefined) updates.taxesCurrent = String(body.taxesCurrent);
  if (body.deductionsCurrent !== undefined) updates.deductionsCurrent = String(body.deductionsCurrent);
  if (body.netCurrent !== undefined) updates.netCurrent = String(body.netCurrent);
  if (body.grossYtd !== undefined) updates.grossYtd = body.grossYtd != null ? String(body.grossYtd) : null;
  if (body.taxesYtd !== undefined) updates.taxesYtd = body.taxesYtd != null ? String(body.taxesYtd) : null;
  if (body.deductionsYtd !== undefined) updates.deductionsYtd = body.deductionsYtd != null ? String(body.deductionsYtd) : null;
  if (body.source !== undefined) updates.source = body.source;
  if (body.isAutoGenerated !== undefined) updates.isAutoGenerated = body.isAutoGenerated;
  if (body.mappingId !== undefined) updates.mappingId = body.mappingId;

  if (Object.keys(updates).length === 0) {
    return Response.json({ error: 'No valid fields to update' }, { status: 400 });
  }

  updates.updatedAt = new Date();

  const [updated] = await db
    .update(paystubs)
    .set(updates)
    .where(eq(paystubs.id, id))
    .returning();

  return Response.json(updated);
}

export async function DELETE(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  const dataUserId = session?.user ? ((session.user as any).dataUserId ?? session.user.id) : undefined;
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const { id } = await params;

  // Verify ownership
  const [existing] = await db
    .select()
    .from(paystubs)
    .where(and(eq(paystubs.id, id), eq(paystubs.userId, dataUserId)))
    .limit(1);

  if (!existing) {
    return Response.json({ error: 'Paystub not found' }, { status: 404 });
  }

  // Delete all transactions linked to this paystub
  await db
    .delete(transactions)
    .where(
      and(eq(transactions.paystubId, id), eq(transactions.userId, dataUserId))
    );

  // Delete the paystub (cascade will delete line items)
  await db.delete(paystubs).where(eq(paystubs.id, id));

  invalidateUserSearchCache(dataUserId);
  return Response.json({ success: true });
}
