import { auth } from 'auth';
import { getDb } from '@/lib/db';
import { paystubs, paystubLineItems, transactions } from '@/lib/db/schema';
import { eq, and, inArray } from 'drizzle-orm';
import { invalidateUserSearchCache } from '@/lib/services/search-cache';
import {
  updateCategorySpendingSummaries,
  updateCategoryIncomeSummaries,
  updateMonthlyCashFlowSummaries,
} from '@/lib/services/sync';
import { getSessionDEK } from '@/lib/crypto-context';

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  const dataUserId = session?.user ? ((session.user as any).dataUserId ?? session.user.id) : undefined;
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const { id } = await params;

  const [paystub] = await db
    .select()
    .from(paystubs)
    .where(and(eq(paystubs.id, id), eq(paystubs.userId, dataUserId)))
    .limit(1);

  if (!paystub) {
    return Response.json({ error: 'Paystub not found' }, { status: 404 });
  }

  const lineItems = await db
    .select()
    .from(paystubLineItems)
    .where(eq(paystubLineItems.paystubId, id));

  return Response.json({ ...paystub, lineItems });
}

export async function PATCH(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  const dataUserId = session?.user ? ((session.user as any).dataUserId ?? session.user.id) : undefined;
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const { id } = await params;

  // Verify ownership
  const [existing] = await db
    .select()
    .from(paystubs)
    .where(and(eq(paystubs.id, id), eq(paystubs.userId, dataUserId)))
    .limit(1);

  if (!existing) {
    return Response.json({ error: 'Paystub not found' }, { status: 404 });
  }

  let body: Record<string, any>;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: 'Invalid request body' }, { status: 400 });
  }

  const updates: Record<string, any> = {};
  if (body.employerName !== undefined) updates.employerName = body.employerName;
  if (body.employeeName !== undefined) updates.employeeName = body.employeeName;
  if (body.payPeriodStart !== undefined) updates.payPeriodStart = body.payPeriodStart;
  if (body.payPeriodEnd !== undefined) updates.payPeriodEnd = body.payPeriodEnd;
  if (body.checkDate !== undefined) updates.checkDate = body.checkDate;
  if (body.adviceNumber !== undefined) updates.adviceNumber = body.adviceNumber;
  if (body.grossCurrent !== undefined) updates.grossCurrent = String(body.grossCurrent);
  if (body.taxesCurrent !== undefined) updates.taxesCurrent = String(body.taxesCurrent);
  if (body.deductionsCurrent !== undefined) updates.deductionsCurrent = String(body.deductionsCurrent);
  if (body.netCurrent !== undefined) updates.netCurrent = String(body.netCurrent);
  if (body.grossYtd !== undefined) updates.grossYtd = body.grossYtd != null ? String(body.grossYtd) : null;
  if (body.taxesYtd !== undefined) updates.taxesYtd = body.taxesYtd != null ? String(body.taxesYtd) : null;
  if (body.deductionsYtd !== undefined) updates.deductionsYtd = body.deductionsYtd != null ? String(body.deductionsYtd) : null;
  if (body.source !== undefined) updates.source = body.source;
  if (body.isAutoGenerated !== undefined) updates.isAutoGenerated = body.isAutoGenerated;
  if (body.mappingId !== undefined) updates.mappingId = body.mappingId;

  // Update line items if provided
  const dek = await getSessionDEK().catch(() => undefined);
  if (Array.isArray(body.lineItems) && body.lineItems.length > 0) {

    for (const item of body.lineItems) {
      if (!item.id) continue;
      const liUpdates: Record<string, any> = {};
      if (item.amount !== undefined) liUpdates.amount = String(item.amount);
      if (item.categoryId !== undefined) liUpdates.categoryId = item.categoryId || null;
      if (Object.keys(liUpdates).length === 0) continue;

      await db
        .update(paystubLineItems)
        .set(liUpdates)
        .where(
          and(
            eq(paystubLineItems.id, item.id),
            eq(paystubLineItems.paystubId, id),
          )
        );
    }

    // Recalculate paystub summary fields from line items
    const allLineItems = await db
      .select()
      .from(paystubLineItems)
      .where(eq(paystubLineItems.paystubId, id));

    let gross = 0;
    let taxes = 0;
    let deductions = 0;

    for (const li of allLineItems) {
      const amt = parseFloat(li.amount || '0');
      switch (li.section) {
        case 'earnings':
          gross += amt;
          break;
        case 'taxes':
          taxes += amt;
          break;
        case 'before_tax_deductions':
        case 'after_tax_deductions':
          deductions += amt;
          break;
      }
    }

    updates.grossCurrent = String(gross);
    updates.taxesCurrent = String(taxes);
    updates.deductionsCurrent = String(deductions);
    updates.netCurrent = String(gross - taxes - deductions);

    // Update linked transactions

    // Earnings: all earnings items share one transaction — recalculate total
    const earningsItems = allLineItems.filter((li) => li.section === 'earnings' && li.transactionId);
    if (earningsItems.length > 0) {
      const earningsTotal = earningsItems.reduce((sum, li) => sum + parseFloat(li.amount || '0'), 0);
      const txnId = earningsItems[0].transactionId!;
      if (dek) {
        const txnValues = { amount: String(earningsTotal) };
        const { encryptRow } = await import('@/lib/crypto');
        const encrypted = await encryptRow('transactions', txnValues, dek);
        await db
          .update(transactions)
          .set(encrypted)
          .where(and(eq(transactions.id, txnId), eq(transactions.userId, dataUserId)));
      } else {
        await db
          .update(transactions)
          .set({ amount: String(earningsTotal) })
          .where(and(eq(transactions.id, txnId), eq(transactions.userId, dataUserId)));
      }
    }

    // Taxes & deductions: each item may have its own transaction
    for (const li of allLineItems) {
      if (li.section === 'earnings' || !li.transactionId) continue;
      const amt = parseFloat(li.amount || '0');
      const negativeAmount = -Math.abs(amt);
      if (dek) {
        const txnValues = { amount: String(negativeAmount) };
        const { encryptRow } = await import('@/lib/crypto');
        const encrypted = await encryptRow('transactions', txnValues, dek);
        await db
          .update(transactions)
          .set(encrypted)
          .where(and(eq(transactions.id, li.transactionId), eq(transactions.userId, dataUserId)));
      } else {
        await db
          .update(transactions)
          .set({ amount: String(negativeAmount) })
          .where(and(eq(transactions.id, li.transactionId), eq(transactions.userId, dataUserId)));
      }
    }
  }

  if (Object.keys(updates).length === 0) {
    return Response.json({ error: 'No valid fields to update' }, { status: 400 });
  }

  updates.updatedAt = new Date();

  const [updated] = await db
    .update(paystubs)
    .set(updates)
    .where(eq(paystubs.id, id))
    .returning();

  // Re-fetch line items to return full state
  const finalLineItems = await db
    .select()
    .from(paystubLineItems)
    .where(eq(paystubLineItems.paystubId, id));

  // Refresh summaries
  if (dek) {
    await updateCategorySpendingSummaries(dataUserId, dek).catch(() => {});
    await updateCategoryIncomeSummaries(dataUserId, dek).catch(() => {});
    await updateMonthlyCashFlowSummaries(dataUserId, dek).catch(() => {});
  }

  invalidateUserSearchCache(dataUserId);
  return Response.json({ ...updated, lineItems: finalLineItems });
}

export async function DELETE(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  const dataUserId = session?.user ? ((session.user as any).dataUserId ?? session.user.id) : undefined;
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const { id } = await params;

  // Verify ownership
  const [existing] = await db
    .select()
    .from(paystubs)
    .where(and(eq(paystubs.id, id), eq(paystubs.userId, dataUserId)))
    .limit(1);

  if (!existing) {
    return Response.json({ error: 'Paystub not found' }, { status: 404 });
  }

  // Delete all transactions linked to this paystub
  await db
    .delete(transactions)
    .where(
      and(eq(transactions.paystubId, id), eq(transactions.userId, dataUserId))
    );

  // Delete the paystub (cascade will delete line items)
  await db.delete(paystubs).where(eq(paystubs.id, id));

  invalidateUserSearchCache(dataUserId);
  return Response.json({ success: true });
}
