import { getDb } from '@/lib/db';
import {
  paystubAutoGenerateSettings,
  paystubs,
  paystubLineItems,
  paystubFieldMappings,
  transactions,
} from '@/lib/db/schema';
import { eq, and, desc, sql } from 'drizzle-orm';
import { createTransactionsFromLineItems } from '@/app/api/paystubs/route';
import {
  updateCategorySpendingSummaries,
  updateCategoryIncomeSummaries,
  updateMonthlyCashFlowSummaries,
} from '@/lib/services/sync';
import {
  addFrequencyInterval,
  getFrequencyDays,
  capOasdiAmount,
  computeOasdiYtdBefore,
  isOasdiLine,
    nextCadenceDate,
  type OasdiYtdState,
} from '@/lib/utils/paystub';
import { DEFAULT_2026_RULES } from '@/lib/constants/retirement-defaults';
import { logger } from '@/lib/logger';
import { invalidateUserSearchCache } from '@/lib/services/search-cache';

const LOG_TAG = '[paystub-auto-generate]';

async function deletePaystubAndTransactions(db: any, paystubId: string, userId: string): Promise<void> {
  // Delete all transactions linked to this paystub
  await db
    .delete(transactions)
    .where(
      and(
        eq(transactions.paystubId, paystubId),
        eq(transactions.userId, userId)
      )
    );
  // Delete the paystub itself (cascades to line items in the DB)
  await db
    .delete(paystubs)
    .where(
      and(
        eq(paystubs.id, paystubId),
        eq(paystubs.userId, userId)
      )
    );
}

function getDaysDiff(dateStr1: string, dateStr2: string): number {
  const d1 = new Date(dateStr1 + 'T00:00:00Z');
  const d2 = new Date(dateStr2 + 'T00:00:00Z');
  return Math.abs(Math.round((d1.getTime() - d2.getTime()) / (1000 * 60 * 60 * 24)));
}

function findExistingPaystub(paystubsList: any[], expectedDate: string) {
  return paystubsList.find(p => getDaysDiff(p.checkDate, expectedDate) <= 2);
}

/**
 * ── S-3: template resolution. ─────────────────────────────────────────────
 * A generation template must be a user-IMPORTED stub (isAutoGenerated=false).
 * The previous behavior used the nearest prior stub of any kind, so a one-off
 * bonus/OT paycheck became the template for every following auto-stub until
 * the next import arrived, tainting the income level indefinitely.
 */
function findMostRecentImportedBefore(paystubsList: any[], date: string) {
  const past = paystubsList.filter(p => p.checkDate < date && !p.isAutoGenerated);
  if (past.length === 0) return null;
  return past[past.length - 1];
}

function shouldRegenerate(
  existing: any,
  existingLineItems: any[],
  template: any,
  templateLineItems: any[],
  mappingsJson: Record<string, { action: string; categoryId: string | null }>
): boolean {
  if (
    existing.employerName !== template.employerName ||
    existing.employeeName !== template.employeeName ||
    existing.grossCurrent !== template.grossCurrent ||
    existing.taxesCurrent !== template.taxesCurrent ||
    existing.deductionsCurrent !== template.deductionsCurrent ||
    existing.netCurrent !== template.netCurrent ||
    existing.mappingId !== template.mappingId
  ) {
    return true;
  }

  if (existingLineItems.length !== templateLineItems.length) {
    return true;
  }

  const sortFn = (a: any, b: any) => {
    const secComp = a.section.localeCompare(b.section);
    if (secComp !== 0) return secComp;
    return a.description.localeCompare(b.description);
  };

  const sortedExisting = [...existingLineItems].sort(sortFn);
  const sortedTemplate = [...templateLineItems].sort(sortFn);

  for (let i = 0; i < sortedExisting.length; i++) {
    const e = sortedExisting[i];
    const t = sortedTemplate[i];

    const lookupKey = `${t.section}:${t.description}`;
    const mappingEntry = mappingsJson[lookupKey];
    const expectedAction = mappingEntry?.action || t.mappingAction || 'import';
    const expectedCategoryId = mappingEntry?.categoryId ?? t.categoryId;

    if (
      e.section !== t.section ||
      e.description !== t.description ||
      e.amount !== t.amount ||
      e.hours !== t.hours ||
      e.rate !== t.rate ||
      e.mappingAction !== expectedAction ||
      e.categoryId !== expectedCategoryId
    ) {
      return true;
    }
  }

  return false;
}

async function generatePaystub(
  db: any,
  effectiveUserId: string,
  template: any,
  templateLineItems: any[],
  basePaystub: any,
  newCheckDate: string,
  setting: any,
  dek: Uint8Array,
  mappingsJson: Record<string, { action: string; categoryId: string | null }>,
  oasdiYtdBefore?: OasdiYtdState,
) {
  const baseCheckDate = new Date(basePaystub.checkDate + 'T00:00:00Z');
  const basePeriodStart = new Date(basePaystub.payPeriodStart + 'T00:00:00Z');
  const basePeriodEnd = new Date(basePaystub.payPeriodEnd + 'T00:00:00Z');
  const nextDate = new Date(newCheckDate + 'T00:00:00Z');
  const daysDiff = Math.round(
    (nextDate.getTime() - baseCheckDate.getTime()) / (1000 * 60 * 60 * 24)
  );

  const newPeriodStart = new Date(basePeriodStart.getTime() + daysDiff * 86400000)
    .toISOString()
    .split('T')[0];
  const newPeriodEnd = new Date(basePeriodEnd.getTime() + daysDiff * 86400000)
    .toISOString()
    .split('T')[0];

  // ── P-1: OASDI (Social Security) annual wage-base cap ─────────────────
  // OASDI is 6.2% on the first $ssWageBaseCap of wages per calendar year
  // (IRC 3121(a) / SSA cap, $184,500 for 2026). A template stub's OASDI line
  // is only correct while cumulative YTD wages remain inside the base; once
  // the base is exhausted the line must roll off. We cap the OASDI line
  // accordingly and stamp a realistic ytdAmount.
  const oasdiWageBaseCap = DEFAULT_2026_RULES.ficaRules.ssWageBaseCap;
  const oasdiRate = DEFAULT_2026_RULES.ficaRules.ssTaxRate;
  const grossCurrent = Number(template.grossCurrent) || 0;

  // Resolve final line-item amounts BEFORE inserting so header totals below
  // reflect the capped OASDI (not the stale template values).
  const resolvedItems = templateLineItems.map((item: any) => {
    const lookupKey = `${item.section}:${item.description}`;
    const mappingEntry = mappingsJson[lookupKey];
    const mappingAction = mappingEntry?.action || item.mappingAction || 'import';
    const categoryId = mappingEntry?.categoryId ?? item.categoryId;

    let amount: string = String(item.amount ?? '0');
    let ytdAmount: string | null = null;
    if (isOasdiLine(item.section, item.description) && oasdiYtdBefore) {
      const expectedOasdi = Number(item.amount) || 0;
      const capped = capOasdiAmount({
        expectedOasdi,
        gross: grossCurrent,
        ytd: oasdiYtdBefore,
        wageBaseCap: oasdiWageBaseCap,
        oasdiRate,
      });
      amount = capped.toFixed(2);
      ytdAmount = (oasdiYtdBefore.oasdiBefore + capped).toFixed(2);
    }

    return { ...item, amount, ytdAmount, mappingAction, categoryId };
  });

  // Recompute a header total only when the template actually contains lines
  // in that section — sparse templates must not have their stored totals
  // zeroed. Net is only derivable when taxes or deduction lines exist.
  const r2 = (n: number) => Math.round(n * 100) / 100;
  const fmt = (n: number) => (Math.round(n * 100) / 100).toFixed(2);
  const sumSections = (sections: string[]) =>
    r2(resolvedItems.filter(i => sections.includes(i.section)).reduce((s, i) => s + (Number(i.amount) || 0), 0));
  const hasEarningsLines = resolvedItems.some(i => i.section === 'earnings');
  const hasTaxLines = resolvedItems.some(i => i.section === 'taxes');
  const hasDeductionLines = resolvedItems.some(i => i.section === 'before_tax_deductions' || i.section === 'after_tax_deductions');
  const effGross = hasEarningsLines ? sumSections(['earnings']) : (Number(template.grossCurrent) || 0);
  const effTaxes = hasTaxLines ? sumSections(['taxes']) : (Number(template.taxesCurrent) || 0);
  const effDeductions = hasDeductionLines ? sumSections(['before_tax_deductions', 'after_tax_deductions']) : (Number(template.deductionsCurrent) || 0);

  const [newPaystub] = await db
    .insert(paystubs)
    .values({
      userId: effectiveUserId,
      employerName: template.employerName,
      employeeName: template.employeeName,
      payPeriodStart: newPeriodStart,
      payPeriodEnd: newPeriodEnd,
      checkDate: newCheckDate,
      adviceNumber: null,
      grossCurrent: hasEarningsLines ? fmt(effGross) : template.grossCurrent,
      taxesCurrent: hasTaxLines ? fmt(effTaxes) : template.taxesCurrent,
      deductionsCurrent: hasDeductionLines ? fmt(effDeductions) : template.deductionsCurrent,
      netCurrent: (hasTaxLines || hasDeductionLines) ? fmt(effGross - effTaxes - effDeductions) : template.netCurrent,
      grossYtd: null,
      taxesYtd: null,
      deductionsYtd: null,
      source: 'auto_generated',
      isAutoGenerated: true,
      mappingId: setting.mappingId,
    })
    .returning();

  const clonedLineItems: any[] = [];
  for (const item of resolvedItems) {
    const [cloned] = await db
      .insert(paystubLineItems)
      .values({
        paystubId: newPaystub.id,
        userId: effectiveUserId,
        section: item.section,
        description: item.description,
        amount: item.amount,
        ytdAmount: item.ytdAmount,
        hours: item.hours,
        rate: item.rate,
        ytdHours: null,
        mappingAction: item.mappingAction,
        categoryId: item.categoryId,
      })
      .returning();

    clonedLineItems.push(cloned);
  }

  await createTransactionsFromLineItems(
    db,
    effectiveUserId,
    newPaystub,
    clonedLineItems,
    template.employerName,
    newCheckDate,
    dek,
  );

  return { ...newPaystub, lineItems: clonedLineItems };
}

export async function runAutoGenerate(
  userId: string,
  dek: Uint8Array,
  dataUserId?: string,
  force?: boolean,
): Promise<number> {
  const db = getDb();
  const effectiveUserId = dataUserId ?? userId;
  const today = new Date().toISOString().split('T')[0];

  let generated = 0;
  let didAnyDeletion = false;

  await db.transaction(async (tx) => {
    // Acquire advisory xact lock for this user to serialize cross-process execution
    if (typeof (tx as any).execute === 'function') {
      try {
        await (tx as any).execute(sql`SELECT pg_advisory_xact_lock(hashtext('paystub-auto-gen:' || ${effectiveUserId}))`);
      } catch (lockErr) {
        logger.debug(`${LOG_TAG} Advisory lock skipped or unsupported`, { error: String(lockErr) });
      }
    }

    const settings = await tx
      .select()
      .from(paystubAutoGenerateSettings)
      .where(
        and(
          eq(paystubAutoGenerateSettings.userId, effectiveUserId),
          eq(paystubAutoGenerateSettings.isEnabled, true),
        )
      );

    for (const setting of settings) {
      // Resolve the base (template) paystub
      let basePaystub = null;
      if (setting.basePaystubId) {
        const [found] = await tx
          .select()
          .from(paystubs)
          .where(
            and(eq(paystubs.id, setting.basePaystubId), eq(paystubs.userId, effectiveUserId))
          )
          .limit(1);
        basePaystub = found;
      }
      if (!basePaystub) {
        // Fall back to most recent imported paystub
        const [latest] = await tx
          .select()
          .from(paystubs)
          .where(
            and(eq(paystubs.userId, effectiveUserId), eq(paystubs.isAutoGenerated, false))
          )
          .orderBy(desc(paystubs.checkDate))
          .limit(1);
        basePaystub = latest;
      }
      if (!basePaystub) continue;

      const baseLineItems = await tx
        .select()
        .from(paystubLineItems)
        .where(eq(paystubLineItems.paystubId, basePaystub.id));

      // Fetch all user paystubs & line items to build state in-memory
      let allUserPaystubs = await tx
        .select()
        .from(paystubs)
        .where(eq(paystubs.userId, effectiveUserId))
        .orderBy(paystubs.checkDate);

      const allLineItems = await tx
        .select()
        .from(paystubLineItems)
        .where(eq(paystubLineItems.userId, effectiveUserId));

      const lineItemsMap = new Map<string, any[]>();
      for (const item of allLineItems) {
        if (!lineItemsMap.has(item.paystubId)) {
          lineItemsMap.set(item.paystubId, []);
        }
        lineItemsMap.get(item.paystubId)!.push(item);
      }

      const [mapping] = await tx
        .select()
        .from(paystubFieldMappings)
        .where(eq(paystubFieldMappings.id, setting.mappingId))
        .limit(1);
      const mappingsJson = (mapping?.mappings || {}) as Record<string, { action: string; categoryId: string | null }>;

      let currentReferenceDate = basePaystub.checkDate;
      // ── S-1: cadence-aware stepping (semimonthly stays on its calendar
      // anchors; other frequencies keep a fixed interval).
      let nextExpectedDate = nextCadenceDate(currentReferenceDate, setting.frequency);
      let settingGenerated = 0;

      while (nextExpectedDate <= today || (force && settingGenerated === 0)) {
        const existing = findExistingPaystub(allUserPaystubs, nextExpectedDate);

        if (existing) {
          if (existing.isAutoGenerated) {
            // ── S-3: template = most recent IMPORTED stub before this date
            // (falls back to the base paystub). A bonus/OT one-off must never
            // become the template for subsequent stubs.
            let template = findMostRecentImportedBefore(allUserPaystubs, existing.checkDate);
            let templateLineItems = [];
            if (template) {
              templateLineItems = lineItemsMap.get(template.id) || [];
            } else {
              template = basePaystub;
              templateLineItems = baseLineItems;
            }

            const existingLineItems = lineItemsMap.get(existing.id) || [];

            if (shouldRegenerate(existing, existingLineItems, template, templateLineItems, mappingsJson)) {
              await deletePaystubAndTransactions(tx, existing.id, effectiveUserId);
              didAnyDeletion = true;

              allUserPaystubs = allUserPaystubs.filter(p => p.id !== existing.id);
              lineItemsMap.delete(existing.id);

              // ── P-1: YTD state for the regenerated stub. Computed AFTER the
              // old stub is removed from the in-memory list so it is not
              // double-counted; counts all stubs strictly before this check
              // date in the same calendar year.
              const regenOasdiYtd = computeOasdiYtdBefore(allUserPaystubs, lineItemsMap, nextExpectedDate);

              const newPaystub = await generatePaystub(
                tx,
                effectiveUserId,
                template,
                templateLineItems,
                basePaystub,
                nextExpectedDate,
                setting,
                dek,
                mappingsJson,
                regenOasdiYtd
              );

              allUserPaystubs.push(newPaystub);
              allUserPaystubs.sort((a, b) => a.checkDate.localeCompare(b.checkDate));
              lineItemsMap.set(newPaystub.id, newPaystub.lineItems);

              settingGenerated++;
              generated++;
            }
          }
          currentReferenceDate = existing.checkDate;
        } else {
          // Missed paystub! Generate it.
          // ── S-3: same template rule as the regeneration branch.
          let template = findMostRecentImportedBefore(allUserPaystubs, nextExpectedDate);
          let templateLineItems = [];
          if (template) {
            templateLineItems = lineItemsMap.get(template.id) || [];
          } else {
            template = basePaystub;
            templateLineItems = baseLineItems;
          }

          // ── P-1: YTD state for the missing stub (all prior stubs in the
          // calendar year; the new stub is not in the list yet).
          const missOasdiYtd = computeOasdiYtdBefore(allUserPaystubs, lineItemsMap, nextExpectedDate);

          const newPaystub = await generatePaystub(
            tx,
            effectiveUserId,
            template,
            templateLineItems,
            basePaystub,
            nextExpectedDate,
            setting,
            dek,
            mappingsJson,
            missOasdiYtd
          );

          allUserPaystubs.push(newPaystub);
          allUserPaystubs.sort((a, b) => a.checkDate.localeCompare(b.checkDate));
          lineItemsMap.set(newPaystub.id, newPaystub.lineItems);

          currentReferenceDate = nextExpectedDate;
          settingGenerated++;
          generated++;
        }

        nextExpectedDate = nextCadenceDate(currentReferenceDate, setting.frequency);
      }

      // Update the lastGeneratedDate setting to reflect the latest check date processed
      const latestPaystub = allUserPaystubs[allUserPaystubs.length - 1];
      if (latestPaystub) {
        await tx
          .update(paystubAutoGenerateSettings)
          .set({
            lastGeneratedDate: latestPaystub.checkDate,
            updatedAt: new Date(),
          })
          .where(eq(paystubAutoGenerateSettings.id, setting.id));
      }
    }
  });

  if (generated > 0 || didAnyDeletion) {
    await updateCategorySpendingSummaries(effectiveUserId, dek);
    await updateCategoryIncomeSummaries(effectiveUserId, dek);
    await updateMonthlyCashFlowSummaries(effectiveUserId, dek);
    invalidateUserSearchCache(effectiveUserId);

    logger.info(`${LOG_TAG} Finished cycle. Generated/Regenerated ${generated} paystubs`, {
      userId: effectiveUserId,
      count: generated,
    });
  }

  return generated;
}
