import { getDb } from '@/lib/db';
import {
  paystubAutoGenerateSettings,
  paystubs,
  paystubLineItems,
  paystubFieldMappings,
} from '@/lib/db/schema';
import { eq, and, desc } from 'drizzle-orm';
import { createTransactionsFromLineItems } from '@/app/api/paystubs/route';
import {
  updateCategorySpendingSummaries,
  updateCategoryIncomeSummaries,
  updateMonthlyCashFlowSummaries,
} from '@/lib/services/sync';
import { addFrequencyInterval, getFrequencyDays } from '@/lib/utils/paystub';
import { logger } from '@/lib/logger';

const LOG_TAG = '[paystub-auto-generate]';

export async function runAutoGenerate(
  userId: string,
  dek: Uint8Array,
  dataUserId?: string,
  force?: boolean,
): Promise<number> {
  const db = getDb();
  const effectiveUserId = dataUserId ?? userId;
  const today = new Date().toISOString().split('T')[0];

  const settings = await db
    .select()
    .from(paystubAutoGenerateSettings)
    .where(
      and(
        eq(paystubAutoGenerateSettings.userId, effectiveUserId),
        eq(paystubAutoGenerateSettings.isEnabled, true),
      )
    );

  let generated = 0;

  for (const setting of settings) {
    // Resolve the base (template) paystub
    let basePaystub = null;
    if (setting.basePaystubId) {
      const [found] = await db
        .select()
        .from(paystubs)
        .where(
          and(eq(paystubs.id, setting.basePaystubId), eq(paystubs.userId, effectiveUserId))
        )
        .limit(1);
      basePaystub = found;
    }
    if (!basePaystub) {
      // Fall back to most recent imported paystub
      const [latest] = await db
        .select()
        .from(paystubs)
        .where(
          and(eq(paystubs.userId, effectiveUserId), eq(paystubs.isAutoGenerated, false))
        )
        .orderBy(desc(paystubs.checkDate))
        .limit(1);
      basePaystub = latest;
    }
    if (!basePaystub) continue;

    const baseLineItems = await db
      .select()
      .from(paystubLineItems)
      .where(eq(paystubLineItems.paystubId, basePaystub.id));

    const [mapping] = await db
      .select()
      .from(paystubFieldMappings)
      .where(eq(paystubFieldMappings.id, setting.mappingId))
      .limit(1);

    const frequencyDays = getFrequencyDays(setting.frequency);
    const baseCheckDate = new Date(basePaystub.checkDate + 'T00:00:00Z');
    const basePeriodStart = new Date(basePaystub.payPeriodStart + 'T00:00:00Z');
    const basePeriodEnd = new Date(basePaystub.payPeriodEnd + 'T00:00:00Z');

    let currentReferenceDate = setting.lastGeneratedDate || basePaystub.checkDate;
    let nextExpectedDate = addFrequencyInterval(currentReferenceDate, setting.frequency);
    let settingGenerated = 0;

    while (nextExpectedDate <= today || (force && settingGenerated === 0)) {
      const nextDate = new Date(nextExpectedDate + 'T00:00:00Z');
      const daysDiff = Math.round(
        (nextDate.getTime() - baseCheckDate.getTime()) / (1000 * 60 * 60 * 24)
      );

      const newCheckDate = nextExpectedDate;
      const newPeriodStart = new Date(basePeriodStart.getTime() + daysDiff * 86400000)
        .toISOString()
        .split('T')[0];
      const newPeriodEnd = new Date(basePeriodEnd.getTime() + daysDiff * 86400000)
        .toISOString()
        .split('T')[0];

      const [newPaystub] = await db
        .insert(paystubs)
        .values({
          userId: effectiveUserId,
          employerName: basePaystub.employerName,
          employeeName: basePaystub.employeeName,
          payPeriodStart: newPeriodStart,
          payPeriodEnd: newPeriodEnd,
          checkDate: newCheckDate,
          adviceNumber: null,
          grossCurrent: basePaystub.grossCurrent,
          taxesCurrent: basePaystub.taxesCurrent,
          deductionsCurrent: basePaystub.deductionsCurrent,
          netCurrent: basePaystub.netCurrent,
          grossYtd: null,
          taxesYtd: null,
          deductionsYtd: null,
          source: 'auto_generated',
          isAutoGenerated: true,
          mappingId: setting.mappingId,
        })
        .returning();

      // Apply field mapping rules to determine mappingAction and categoryId
      const mappingsJson: Record<string, { action: string; categoryId: string | null }> = (mapping?.mappings as Record<string, { action: string; categoryId: string | null }>) || {};

      const clonedLineItems: Array<{
        id: string;
        section: string;
        description: string;
        amount: string;
        mappingAction: string;
        categoryId: string | null;
      }> = [];

      for (const baseItem of baseLineItems) {
        // Look up the line item in the field mapping rules
        const lookupKey = `${baseItem.section}:${baseItem.description}`;
        const mappingEntry = mappingsJson[lookupKey];

        // Use mapping rules if available, otherwise fall back to base item values
        const mappingAction = mappingEntry?.action || baseItem.mappingAction || 'import';
        const categoryId = mappingEntry?.categoryId ?? baseItem.categoryId;

        const [cloned] = await db
          .insert(paystubLineItems)
          .values({
            paystubId: newPaystub.id,
            userId: effectiveUserId,
            section: baseItem.section,
            description: baseItem.description,
            amount: baseItem.amount,
            ytdAmount: null,
            hours: baseItem.hours,
            rate: baseItem.rate,
            ytdHours: null,
            mappingAction: mappingAction,
            categoryId: categoryId,
          })
          .returning();

        clonedLineItems.push(cloned);
      }

      await createTransactionsFromLineItems(
        db,
        effectiveUserId,
        newPaystub,
        clonedLineItems,
        basePaystub.employerName,
        newCheckDate,
        dek,
      );

      await db
        .update(paystubAutoGenerateSettings)
        .set({
          lastGeneratedDate: newCheckDate,
          updatedAt: new Date(),
        })
        .where(eq(paystubAutoGenerateSettings.id, setting.id));

      settingGenerated++;
      generated++;

      // Advance dates for next loop iteration
      currentReferenceDate = newCheckDate;
      nextExpectedDate = addFrequencyInterval(currentReferenceDate, setting.frequency);
    }
  }

  if (generated > 0) {
    await updateCategorySpendingSummaries(effectiveUserId, dek);
    await updateCategoryIncomeSummaries(effectiveUserId, dek);
    await updateMonthlyCashFlowSummaries(effectiveUserId, dek);

    logger.info(`${LOG_TAG} Auto-generated ${generated} paystubs`, {
      userId: effectiveUserId,
      count: generated,
    });
  }

  return generated;
}
