ALTER TABLE budgets ADD COLUMN IF NOT EXISTS period_type TEXT NOT NULL DEFAULT 'monthly';
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS period_key TEXT;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS funding_account_id UUID REFERENCES accounts(id) ON DELETE SET NULL;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS rollover BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS notes TEXT;
