import { eq, and, inArray, gte, lte } from 'drizzle-orm';
/**
 * GET /api/paystubs/deposit-report  —  S-2 read-only deposit reconciliation.
 *
 * Cross-checks every auto-generated paystub within the recent window against
 * actual bank deposits, and reports:
 *   - matched:        |deposit − netCurrent| ≤ tolerance (stub confirmed by the bank)
 *   - mismatch:       a deposit exists but differs beyond tolerance (possible
 *                     salary change → suggests importing a fresh paystub)
 *   - missing:        no deposit found in the window (stub may be premature,
 *                     or the income account mapping is wrong)
 *
 * Strictly READ-ONLY: it never creates, edits, or deletes stubs or
 * transactions. The UI surfaces suspects as a suggestion chip; the user's
 * remedy is to import a newer paystub (which drives the existing
 * P-1/S-3 regeneration path), not an automated correction.
 */
import { auth } from 'auth';
import { getDb } from '@/lib/db';
import {
  paystubs,
  paystubFieldMappings,
  transactions,
} from '@/lib/db/schema';
import { decryptRows } from '@/lib/crypto';
import { getSessionDEK } from '@/lib/crypto-context';
import { logger } from '@/lib/logger';

export async function GET() {
  const session = await auth();
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const userId = session.user.id;
  const dataUserId = (session.user as any).dataUserId ?? session.user.id;
  const dek = await getSessionDEK();

  try {
    const today = new Date().toISOString().split('T')[0];
    // Window: report stubs whose check date falls in the last 90 days.
    const windowStart = new Date(Date.now() - 90 * 86400000).toISOString().split('T')[0];

    const stubs = await db
      .select()
      .from(paystubs)
      .where(
        and(
          eq(paystubs.userId, dataUserId),
          eq(paystubs.isAutoGenerated, true),
          gte(paystubs.checkDate, windowStart),
          lte(paystubs.checkDate, today),
        )
      )
      .orderBy(paystubs.checkDate);

    if (stubs.length === 0) {
      return Response.json({ stubCount: 0, results: [] });
    }

    const mappings = await db
      .select({
        id: paystubFieldMappings.id,
        accountId: paystubFieldMappings.accountId,
      })
      .from(paystubFieldMappings)
      .where(eq(paystubFieldMappings.userId, dataUserId));
    const mappingAccountById = new Map(mappings.map(m => [m.id, m.accountId]));
    const incomeAccounts = Array.from(
      new Set(stubs.map(s => mappingAccountById.get(s.mappingId!)).filter((v): v is string => !!v))
    );

    // Candidate deposits: positive, non-deleted bank/manual/import transactions
    // on the mapped accounts inside the stub window (±5 day padding each side).
    const padDate = (d: string, days: number) =>
      new Date(new Date(d + 'T00:00:00Z').getTime() + days * 86400000).toISOString().split('T')[0];
    let candidateTxns: any[] = [];
    if (incomeAccounts.length > 0) {
      candidateTxns = await db
        .select()
        .from(transactions)
        .where(
          and(
            eq(transactions.userId, dataUserId),
            inArray(transactions.accountId, incomeAccounts),
            gte(transactions.date, padDate(windowStart, -5)),
            lte(transactions.date, padDate(today, 5)),
            eq(transactions.deleted, false),
          )
        );
    }
    // Filter in JS: amount is encrypted (string) and may not be comparable in SQL.
    const deposits = (dek ? await decryptRows('transactions', candidateTxns, dek) : candidateTxns)
      .filter(t => incomeAccounts.includes(t.accountId))
      .map(t => ({ ...t, amount: Number(t.amount) }))
      .filter(t => Number.isFinite(t.amount) && t.amount > 0)
      .sort((a, b) => a.date.localeCompare(b.date));

    const TOLERANCE = 0.02; // 2% — beyond this, the bank says the salary moved
    const DATE_WINDOW_DAYS = 5; // deposits usually post ±a few days around check date

    const results: Array<{
      checkDate: string;
      employerName: string;
      netCurrent: string;
      status: 'matched' | 'mismatch' | 'missing';
      bestDeposit: { date: string; amount: number; deltaPct: number } | null;
    }> = [];

    for (const stub of stubs) {
      const net = Number(stub.netCurrent) || 0;
      const from = padDate(stub.checkDate, -DATE_WINDOW_DAYS);
      const to = padDate(stub.checkDate, DATE_WINDOW_DAYS);
      // Best candidate = deposit in window with smallest |Δ|; ties → the one
      // closest in date to the check date.
      let best: { txn: (typeof deposits)[number]; delta: number } | null = null;
      for (const txn of deposits) {
        if (txn.date < from || txn.date > to) continue;
        const delta = Math.abs(txn.amount - net);
        if (
          !best ||
          delta < best.delta ||
          (delta === best.delta &&
            Math.abs(dateDiffDays(txn.date, stub.checkDate)) <
              Math.abs(dateDiffDays(best.txn.date, stub.checkDate)))
        ) {
          best = { txn, delta };
        }
      }

      if (!best) {
        results.push({
          checkDate: stub.checkDate,
          employerName: stub.employerName,
          netCurrent: stub.netCurrent,
          status: 'missing',
          bestDeposit: null,
        });
        continue;
      }

      const deltaPct = net !== 0 ? (best.delta / Math.abs(net)) * 100 : 100;
      results.push({
        checkDate: stub.checkDate,
        employerName: stub.employerName,
        netCurrent: stub.netCurrent,
        status: deltaPct <= TOLERANCE * 100 ? 'matched' : 'mismatch',
        bestDeposit: {
          date: best.txn.date,
          amount: best.txn.amount,
          deltaPct: Math.round(deltaPct * 100) / 100,
        },
      });
    }

    const mismatches = results.filter(r => r.status === 'mismatch').length;
    const missing = results.filter(r => r.status === 'missing').length;

    // Read-only signal: repeated mismatch = probable sustained salary change →
    // suggest the user import a fresh paystub (S-2 "salary-change suspect").
    return Response.json({
      stubCount: stubs.length,
      windowStart,
      results,
      summary: {
        matched: results.length - mismatches - missing,
        mismatch: mismatches,
        missing,
        sustainedSalaryChangeSuspect: mismatches >= 2,
        suggestion:
          mismatches >= 2
            ? 'Bank deposits differ from your generated paychecks in several recent periods. Import a fresh paystub so the generator re-anchors on your current salary.'
            : null,
      },
    });
  } catch (err) {
    logger.error('[paystubs/deposit-report] failed', { error: String(err) });
    return Response.json({ error: 'Failed to build deposit report' }, { status: 500 });
  }
}

function dateDiffDays(a: string, b: string): number {
  return Math.round(
    (new Date(a + 'T00:00:00Z').getTime() - new Date(b + 'T00:00:00Z').getTime()) / 86400000
  );
}
