'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { Switch } from '@/components/ui/switch';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';

// ── Types ────────────────────────────────────────────────────────────────────

type FieldMapping = {
  action: 'import' | 'ignore';
  categoryId: string | null;
};

type MappingTemplate = {
  id: string;
  name: string;
  employerName: string;
  isDefault: boolean;
  mappings: Record<string, FieldMapping>;
  createdAt: string;
};

type Category = {
  id: string;
  name: string;
  parentId: string | null;
  isIncome: boolean;
  categoryType: string;
  color: string;
};

type Paystub = {
  id: string;
  employerName: string;
  employeeName: string | null;
  payPeriodStart: string;
  payPeriodEnd: string;
  checkDate: string;
  adviceNumber: string | null;
  grossCurrent: string;
  taxesCurrent: string;
  deductionsCurrent: string;
  netCurrent: string;
  source: string;
  isAutoGenerated: boolean;
  createdAt: string;
};

type AutoGenerateSettings = {
  id: string;
  mappingId: string;
  isEnabled: boolean;
  frequency: string;
  basePaystubId: string | null;
  lastGeneratedDate: string | null;
};

// ── Component ────────────────────────────────────────────────────────────────

export default function PayrollTab() {
  // ── Feature Toggle State ──
  const [paystubEnabled, setPaystubEnabled] = useState(false);
  const [toggleLoading, setToggleLoading] = useState(false);

  // ── Data State ──
  const [paystubs, setPaystubs] = useState<Paystub[]>([]);
  const [paystubsLoading, setPaystubsLoading] = useState(true);
  const [mappings, setMappings] = useState<MappingTemplate[]>([]);
  const [mappingsLoading, setMappingsLoading] = useState(true);
  const [categories, setCategories] = useState<Category[]>([]);
  const [autoGenSettings, setAutoGenSettings] = useState<AutoGenerateSettings[]>([]);

  // ── Import State ──
  const [importMode, setImportMode] = useState<'idle' | 'upload' | 'mapping' | 'importing' | 'done'>('idle');
  const [importFile, setImportFile] = useState<File | null>(null);
  const [importData, setImportData] = useState<any[]>([]);
  const [importStartDate, setImportStartDate] = useState('');
  const [importEmployerName, setImportEmployerName] = useState('');
  const [selectedMappingId, setSelectedMappingId] = useState<string | null>(null);
  const [importResult, setImportResult] = useState<{ imported: number; skipped: number; total: number } | null>(null);
  const [importError, setImportError] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  // ── Mapping Editor State ──
  const [editingMapping, setEditingMapping] = useState<MappingTemplate | null>(null);
  const [showMappingEditor, setShowMappingEditor] = useState(false);
  const [mappingEditorFields, setMappingEditorFields] = useState<Record<string, FieldMapping>>({});
  const [mappingEditorName, setMappingEditorName] = useState('');
  const [mappingEditorEmployer, setMappingEditorEmployer] = useState('');
  const [mappingSaving, setMappingSaving] = useState(false);

  // ── Auto-Generate Editor ──
  const [showAutoGenEditor, setShowAutoGenEditor] = useState(false);
  const [autoGenMappingId, setAutoGenMappingId] = useState('');
  const [autoGenFrequency, setAutoGenFrequency] = useState('weekly');
  const [autoGenBasePaystubId, setAutoGenBasePaystubId] = useState('');
  const [autoGenEnabled, setAutoGenEnabled] = useState(false);
  const [autoGenSaving, setAutoGenSaving] = useState(false);

  // ── Paystub View ──
  const [viewingPaystub, setViewingPaystub] = useState<any>(null);
  const [paystubFilter, setPaystubFilter] = useState<'all' | 'imported' | 'auto'>('all');

  // ── Delete State ──
  const [deletePaystub, setDeletePaystub] = useState<Paystub | null>(null);
  const [deleteLoading, setDeleteLoading] = useState(false);
  const [deleteMapping, setDeleteMapping] = useState<MappingTemplate | null>(null);
  const [deleteMappingLoading, setDeleteMappingLoading] = useState(false);

  // ── Fetch functions ──

  const fetchSettings = useCallback(async () => {
    try {
      const res = await fetch('/api/user-settings', { credentials: 'include' });
      const data = await res.json();
      setPaystubEnabled(data.paystubEnabled ?? false);
    } catch {}
  }, []);

  const fetchPaystubs = useCallback(async () => {
    setPaystubsLoading(true);
    try {
      const res = await fetch('/api/paystubs?limit=100', { credentials: 'include' });
      const data = await res.json();
      setPaystubs(Array.isArray(data) ? data : []);
    } catch {
      setPaystubs([]);
    } finally {
      setPaystubsLoading(false);
    }
  }, []);

  const fetchMappings = useCallback(async () => {
    setMappingsLoading(true);
    try {
      const res = await fetch('/api/paystubs/mappings', { credentials: 'include' });
      const data = await res.json();
      setMappings(Array.isArray(data) ? data : []);
    } catch {
      setMappings([]);
    } finally {
      setMappingsLoading(false);
    }
  }, []);

  const fetchCategories = useCallback(async () => {
    try {
      const res = await fetch('/api/categories', { credentials: 'include' });
      const data = await res.json();
      setCategories(Array.isArray(data) ? data : []);
    } catch {
      setCategories([]);
    }
  }, []);

  const fetchAutoGenSettings = useCallback(async () => {
    try {
      const res = await fetch('/api/paystubs/auto-generate', { credentials: 'include' });
      const data = await res.json();
      setAutoGenSettings(Array.isArray(data) ? data : []);
    } catch {
      setAutoGenSettings([]);
    }
  }, []);

  useEffect(() => {
    fetchSettings();
    fetchPaystubs();
    fetchMappings();
    fetchCategories();
    fetchAutoGenSettings();
  }, [fetchSettings, fetchPaystubs, fetchMappings, fetchCategories, fetchAutoGenSettings]);

  // ── Toggle handler ──

  const handleToggle = async (enabled: boolean) => {
    setToggleLoading(true);
    try {
      await fetch('/api/user-settings', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ paystubEnabled: enabled }),
      });
      setPaystubEnabled(enabled);
    } catch {}
    setToggleLoading(false);
  };

  // ── Import flow ──

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setImportFile(file);
    setImportError('');

    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const json = JSON.parse(ev.target?.result as string);
        const arr = Array.isArray(json) ? json : [json];
        setImportData(arr);
        setImportMode('upload');

        // Extract unique descriptions to build mapping if needed
        if (arr.length > 0 && mappings.length === 0) {
          const allDescs = extractDescriptions(arr);
          const newFields: Record<string, FieldMapping> = {};
          for (const desc of allDescs) {
            newFields[desc] = { action: 'import', categoryId: null };
          }
          setMappingEditorFields(newFields);
          setMappingEditorName('Default Mapping');
          setMappingEditorEmployer('');
        }
      } catch {
        setImportError('Invalid JSON file. Please upload a valid JSON array of paystubs.');
        setImportMode('idle');
      }
    };
    reader.readAsText(file);
  };

  const extractDescriptions = (data: any[]): string[] => {
    const descs = new Set<string>();
    for (const stub of data) {
      for (const item of stub.hoursAndEarnings ?? []) descs.add(`earnings:${item.description}`);
      for (const item of stub.taxes ?? []) descs.add(`taxes:${item.description}`);
      for (const item of stub.beforeTaxDeductions ?? []) descs.add(`before_tax_deductions:${item.description}`);
      for (const item of stub.afterTaxDeductions ?? []) descs.add(`after_tax_deductions:${item.description}`);
    }
    return Array.from(descs);
  };

  const handleImport = async () => {
    if (!selectedMappingId && mappings.length === 0) {
      setImportError('Please create a field mapping first.');
      return;
    }

    setImportMode('importing');
    setImportError('');

    try {
      const res = await fetch('/api/paystubs/import', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          paystubs: importData,
          mappingId: selectedMappingId || mappings[0]?.id,
          startDate: importStartDate || undefined,
          employerName: importEmployerName || 'Employer',
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Import failed');
      setImportResult(data);
      setImportMode('done');
      fetchPaystubs();
    } catch (err) {
      setImportError(err instanceof Error ? err.message : 'Import failed');
      setImportMode('upload');
    }
  };

  const resetImport = () => {
    setImportMode('idle');
    setImportFile(null);
    setImportData([]);
    setImportStartDate('');
    setImportEmployerName('');
    setImportResult(null);
    setImportError('');
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  // ── Mapping CRUD ──

  const handleSaveMapping = async () => {
    setMappingSaving(true);
    try {
      // Convert the sectioned keys back to flat mappings
      const flatMappings: Record<string, FieldMapping> = {};
      for (const [key, value] of Object.entries(mappingEditorFields)) {
        flatMappings[key] = value;
      }

      if (editingMapping) {
        await fetch(`/api/paystubs/mappings/${editingMapping.id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          credentials: 'include',
          body: JSON.stringify({
            name: mappingEditorName,
            employerName: mappingEditorEmployer,
            mappings: flatMappings,
          }),
        });
      } else {
        await fetch('/api/paystubs/mappings', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          credentials: 'include',
          body: JSON.stringify({
            name: mappingEditorName,
            employerName: mappingEditorEmployer,
            isDefault: mappings.length === 0,
            mappings: flatMappings,
          }),
        });
      }
      setShowMappingEditor(false);
      setEditingMapping(null);
      fetchMappings();
    } catch {}
    setMappingSaving(false);
  };

  const openMappingEditor = (mapping?: MappingTemplate) => {
    if (mapping) {
      setEditingMapping(mapping);
      setMappingEditorName(mapping.name);
      setMappingEditorEmployer(mapping.employerName);
      setMappingEditorFields(mapping.mappings as Record<string, FieldMapping>);
    } else {
      setEditingMapping(null);
      setMappingEditorName('');
      setMappingEditorEmployer('');
      // If we have import data, pre-populate from it
      if (importData.length > 0) {
        const allDescs = extractDescriptions(importData);
        const newFields: Record<string, FieldMapping> = {};
        for (const desc of allDescs) {
          newFields[desc] = { action: 'import', categoryId: null };
        }
        setMappingEditorFields(newFields);
      } else {
        setMappingEditorFields({});
      }
    }
    setShowMappingEditor(true);
  };

  const handleDeleteMapping = async () => {
    if (!deleteMapping) return;
    setDeleteMappingLoading(true);
    try {
      await fetch(`/api/paystubs/mappings/${deleteMapping.id}`, {
        method: 'DELETE',
        credentials: 'include',
      });
      setDeleteMapping(null);
      fetchMappings();
    } catch {}
    setDeleteMappingLoading(false);
  };

  // ── Auto-Generate ──

  const handleSaveAutoGen = async () => {
    setAutoGenSaving(true);
    try {
      await fetch('/api/paystubs/auto-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          mappingId: autoGenMappingId,
          isEnabled: autoGenEnabled,
          frequency: autoGenFrequency,
          basePaystubId: autoGenBasePaystubId || null,
        }),
      });
      setShowAutoGenEditor(false);
      fetchAutoGenSettings();
    } catch {}
    setAutoGenSaving(false);
  };

  // ── Paystub View ──

  const handleViewPaystub = async (id: string) => {
    try {
      const res = await fetch(`/api/paystubs/${id}`, { credentials: 'include' });
      const data = await res.json();
      setViewingPaystub(data);
    } catch {}
  };

  // ── Paystub Delete ──

  const handleDeletePaystub = async () => {
    if (!deletePaystub) return;
    setDeleteLoading(true);
    try {
      await fetch(`/api/paystubs/${deletePaystub.id}`, {
        method: 'DELETE',
        credentials: 'include',
      });
      setDeletePaystub(null);
      fetchPaystubs();
    } catch {}
    setDeleteLoading(false);
  };

  // ── Helpers ──

  const formatCurrency = (val: string | number) => {
    const num = typeof val === 'string' ? parseFloat(val) : val;
    if (isNaN(num)) return '$0.00';
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(num);
  };

  const formatDate = (dateStr: string) => {
    if (!dateStr) return '';
    const d = new Date(dateStr + 'T00:00:00');
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const sectionLabel = (key: string) => {
    const section = key.split(':')[0];
    switch (section) {
      case 'earnings': return 'Earnings';
      case 'taxes': return 'Taxes';
      case 'before_tax_deductions': return 'Pre-Tax Deductions';
      case 'after_tax_deductions': return 'Post-Tax Deductions';
      default: return section;
    }
  };

  const descriptionLabel = (key: string) => key.split(':').slice(1).join(':');

  const groupedMappingKeys = (fields: Record<string, FieldMapping>) => {
    const groups: Record<string, string[]> = {};
    for (const key of Object.keys(fields)) {
      const section = key.split(':')[0];
      if (!groups[section]) groups[section] = [];
      groups[section].push(key);
    }
    return groups;
  };

  const filteredPaystubs = paystubs.filter((p) => {
    if (paystubFilter === 'imported') return !p.isAutoGenerated;
    if (paystubFilter === 'auto') return p.isAutoGenerated;
    return true;
  });

  const getCategoryName = (id: string | null) => {
    if (!id) return '—';
    const cat = categories.find((c) => c.id === id);
    return cat?.name ?? '—';
  };

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="space-y-6">
      {/* Feature Toggle */}
      <div className="p-5 bg-card border border-border rounded-xl">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-base font-semibold text-foreground">Paystub Integration</h2>
            <p className="text-xs text-muted-foreground mt-1">
              {paystubEnabled
                ? 'Paystub data is included in charts and calculations.'
                : 'When disabled, paystub data is hidden from all charts and calculations but remains stored.'}
            </p>
          </div>
          <Switch
            checked={paystubEnabled}
            onCheckedChange={handleToggle}
            disabled={toggleLoading}
          />
        </div>
      </div>

      {/* Import Section */}
      <div className="p-5 bg-card border border-border rounded-xl">
        <h2 className="text-base font-semibold text-foreground mb-4">Import Paystubs</h2>

        {importMode === 'idle' && (
          <div className="space-y-3">
            <div className="flex gap-2">
              <button
                onClick={() => fileInputRef.current?.click()}
                className="px-4 py-2 text-sm font-medium text-primary-foreground bg-primary rounded-lg hover:opacity-90 transition-all"
              >
                📄 Import JSON
              </button>
              <input
                ref={fileInputRef}
                type="file"
                accept=".json"
                onChange={handleFileSelect}
                className="hidden"
              />
            </div>
            {importError && (
              <div className="p-3 bg-destructive/20 border border-destructive/30 rounded-lg">
                <p className="text-destructive text-sm">{importError}</p>
              </div>
            )}
          </div>
        )}

        {importMode === 'upload' && importData.length > 0 && (
          <div className="space-y-4">
            <div className="p-3 bg-primary/5 border border-primary/20 rounded-lg">
              <p className="text-sm text-foreground">
                Found <strong>{importData.length}</strong> paystub{importData.length !== 1 ? 's' : ''} in{' '}
                <span className="font-mono text-xs">{importFile?.name}</span>
              </p>
              {importData.length > 0 && (
                <p className="text-xs text-muted-foreground mt-1">
                  Date range: {importData[importData.length - 1]?.checkDate} — {importData[0]?.checkDate}
                </p>
              )}
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">Employer Name</label>
                <Input
                  value={importEmployerName}
                  onChange={(e) => setImportEmployerName(e.target.value)}
                  placeholder="e.g., Acme Corp"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">Import From (optional)</label>
                <Input
                  type="date"
                  value={importStartDate}
                  onChange={(e) => setImportStartDate(e.target.value)}
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-foreground mb-1">Field Mapping</label>
              {mappings.length > 0 ? (
                <div className="flex items-center gap-2">
                  <select
                    value={selectedMappingId || ''}
                    onChange={(e) => setSelectedMappingId(e.target.value)}
                    className="flex-1 text-sm bg-background border border-border rounded-lg px-3 py-2 text-foreground focus:outline-none focus:ring-1 focus:ring-ring"
                  >
                    {mappings.map((m) => (
                      <option key={m.id} value={m.id}>
                        {m.name} {m.employerName ? `(${m.employerName})` : ''} {m.isDefault ? '★' : ''}
                      </option>
                    ))}
                  </select>
                  <button
                    onClick={() => openMappingEditor(mappings.find((m) => m.id === selectedMappingId) || mappings[0])}
                    className="px-3 py-2 text-xs font-medium text-muted-foreground hover:text-foreground border border-border hover:bg-muted rounded-lg transition-colors"
                  >
                    Edit
                  </button>
                  <button
                    onClick={() => openMappingEditor()}
                    className="px-3 py-2 text-xs font-medium text-primary bg-primary/10 hover:bg-primary/20 rounded-lg transition-colors"
                  >
                    New
                  </button>
                </div>
              ) : (
                <button
                  onClick={() => openMappingEditor()}
                  className="w-full px-4 py-2 text-sm font-medium text-primary bg-primary/10 hover:bg-primary/20 rounded-lg transition-colors border border-primary/20"
                >
                  + Create Field Mapping
                </button>
              )}
            </div>

            {importError && (
              <div className="p-3 bg-destructive/20 border border-destructive/30 rounded-lg">
                <p className="text-destructive text-sm">{importError}</p>
              </div>
            )}

            <div className="flex gap-2">
              <button
                onClick={handleImport}
                disabled={mappings.length === 0}
                className="px-4 py-2 text-sm font-medium text-primary-foreground bg-primary rounded-lg hover:opacity-90 transition-all disabled:opacity-50"
              >
                Import Paystubs
              </button>
              <button
                onClick={resetImport}
                className="px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground border border-border hover:bg-muted rounded-lg transition-colors"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {importMode === 'importing' && (
          <div className="p-4 text-center">
            <div className="text-sm text-muted-foreground animate-pulse">Importing paystubs...</div>
          </div>
        )}

        {importMode === 'done' && importResult && (
          <div className="space-y-3">
            <div className="p-4 bg-chart-1/10 border border-chart-1/20 rounded-lg">
              <p className="text-sm text-chart-1 font-medium">Import Complete</p>
              <div className="text-xs text-chart-1/80 mt-1 space-y-0.5">
                <p>{importResult.imported} paystubs imported</p>
                {importResult.skipped > 0 && <p>{importResult.skipped} skipped (duplicates)</p>}
                <p>{importResult.total} total in file</p>
              </div>
            </div>
            <button
              onClick={resetImport}
              className="px-4 py-2 text-sm font-medium text-muted-foreground hover:text-foreground border border-border hover:bg-muted rounded-lg transition-colors"
            >
              Done
            </button>
          </div>
        )}
      </div>

      {/* Field Mappings List */}
      <div className="p-5 bg-card border border-border rounded-xl">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-base font-semibold text-foreground">Field Mappings</h2>
            <p className="text-xs text-muted-foreground mt-1">
              Define how paystub line items map to categories. Supports multiple employers.
            </p>
          </div>
          <button
            onClick={() => openMappingEditor()}
            className="px-3 py-1.5 text-xs font-medium text-primary bg-primary/10 hover:bg-primary/20 rounded-lg transition-colors"
          >
            + New Mapping
          </button>
        </div>

        {mappingsLoading ? (
          <div className="text-muted-foreground text-sm">Loading...</div>
        ) : mappings.length === 0 ? (
          <p className="text-muted-foreground text-sm">No field mappings yet. Create one to start importing paystubs.</p>
        ) : (
          <div className="space-y-2">
            {mappings.map((m) => (
              <div
                key={m.id}
                className="p-3 bg-muted/30 border border-border rounded-lg flex items-center justify-between"
              >
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-foreground">{m.name}</span>
                    {m.isDefault && (
                      <span className="px-1.5 py-0.5 text-[10px] rounded bg-primary/20 text-primary font-medium">Default</span>
                    )}
                  </div>
                  {m.employerName && (
                    <p className="text-xs text-muted-foreground mt-0.5">{m.employerName}</p>
                  )}
                  <p className="text-xs text-muted-foreground">
                    {Object.keys(m.mappings).length} fields mapped
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => openMappingEditor(m)}
                    className="px-2.5 py-1 text-xs font-medium text-muted-foreground hover:text-foreground border border-border hover:bg-muted rounded-lg transition-colors"
                  >
                    Edit
                  </button>
                  <button
                    onClick={() => setDeleteMapping(m)}
                    className="px-2.5 py-1 text-xs font-medium text-destructive hover:bg-destructive/10 border border-destructive/30 rounded-lg transition-colors"
                  >
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Auto-Generate Section */}
      <div className="p-5 bg-card border border-border rounded-xl">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-base font-semibold text-foreground">Auto-Generate Paystubs</h2>
            <p className="text-xs text-muted-foreground mt-1">
              Automatically create paystubs on each pay date using a template from your most recent stub.
              Auto-generated stubs are clearly marked and separate from imported data.
            </p>
          </div>
        </div>

        {autoGenSettings.length > 0 ? (
          <div className="space-y-2">
            {autoGenSettings.map((ags) => {
              const mapping = mappings.find((m) => m.id === ags.mappingId);
              return (
                <div
                  key={ags.id}
                  className="p-3 bg-muted/30 border border-border rounded-lg flex items-center justify-between"
                >
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-medium text-foreground">
                        {mapping?.name || 'Unknown Mapping'}
                      </span>
                      <span className={`px-1.5 py-0.5 text-[10px] rounded font-medium ${
                        ags.isEnabled ? 'bg-chart-1/20 text-chart-1' : 'bg-muted text-muted-foreground'
                      }`}>
                        {ags.isEnabled ? 'Active' : 'Paused'}
                      </span>
                    </div>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      Frequency: {ags.frequency} · Last generated: {ags.lastGeneratedDate ? formatDate(ags.lastGeneratedDate) : 'Never'}
                    </p>
                  </div>
                  <button
                    onClick={() => {
                      setAutoGenMappingId(ags.mappingId);
                      setAutoGenFrequency(ags.frequency);
                      setAutoGenBasePaystubId(ags.basePaystubId || '');
                      setAutoGenEnabled(ags.isEnabled);
                      setShowAutoGenEditor(true);
                    }}
                    className="px-2.5 py-1 text-xs font-medium text-muted-foreground hover:text-foreground border border-border hover:bg-muted rounded-lg transition-colors"
                  >
                    Edit
                  </button>
                </div>
              );
            })}
          </div>
        ) : (
          <button
            onClick={() => {
              setAutoGenMappingId(mappings[0]?.id || '');
              setAutoGenFrequency('weekly');
              setAutoGenBasePaystubId('');
              setAutoGenEnabled(false);
              setShowAutoGenEditor(true);
            }}
            disabled={mappings.length === 0}
            className="w-full px-4 py-2 text-sm font-medium text-primary bg-primary/10 hover:bg-primary/20 rounded-lg transition-colors border border-primary/20 disabled:opacity-50"
          >
            + Set Up Auto-Generate
          </button>
        )}
      </div>

      {/* Paystub History */}
      <div className="p-5 bg-card border border-border rounded-xl">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-base font-semibold text-foreground">Paystub History</h2>
            <p className="text-xs text-muted-foreground mt-1">
              {paystubs.length} paystub{paystubs.length !== 1 ? 's' : ''} on file
            </p>
          </div>
          <div className="flex rounded-lg bg-muted border border-border overflow-hidden">
            {(['all', 'imported', 'auto'] as const).map((filter) => (
              <button
                key={filter}
                onClick={() => setPaystubFilter(filter)}
                className={`px-3 py-1.5 text-xs font-medium transition-colors ${
                  paystubFilter === filter
                    ? 'bg-primary text-primary-foreground'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                {filter === 'all' ? 'All' : filter === 'imported' ? 'Imported' : 'Auto'}
              </button>
            ))}
          </div>
        </div>

        {paystubsLoading ? (
          <div className="text-muted-foreground text-sm">Loading...</div>
        ) : filteredPaystubs.length === 0 ? (
          <p className="text-muted-foreground text-sm">No paystubs found.</p>
        ) : (
          <div className="space-y-1.5 max-h-[400px] overflow-y-auto">
            {filteredPaystubs.map((p) => (
              <div
                key={p.id}
                className="p-3 bg-muted/30 border border-border rounded-lg flex items-center justify-between hover:bg-muted/50 transition-colors cursor-pointer"
                onClick={() => handleViewPaystub(p.id)}
              >
                <div className="flex items-center gap-3 min-w-0">
                  <span className="text-lg flex-shrink-0">{p.isAutoGenerated ? '🔄' : '📄'}</span>
                  <div className="min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-medium text-foreground">{formatDate(p.checkDate)}</span>
                      {p.isAutoGenerated && (
                        <span className="px-1.5 py-0.5 text-[10px] rounded bg-chart-3/20 text-chart-3 font-medium">Auto</span>
                      )}
                      {p.employerName && (
                        <span className="text-xs text-muted-foreground">{p.employerName}</span>
                      )}
                    </div>
                    <div className="text-xs text-muted-foreground">
                      Gross: <span className="blur-number">{formatCurrency(p.grossCurrent)}</span>
                      {' · '}Net: <span className="blur-number">{formatCurrency(p.netCurrent)}</span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  <button
                    onClick={(e) => { e.stopPropagation(); setDeletePaystub(p); }}
                    className="px-2 py-1 text-xs font-medium text-destructive hover:bg-destructive/10 rounded transition-colors"
                  >
                    ✕
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* ── Mapping Editor Dialog ── */}
      <Dialog open={showMappingEditor} onOpenChange={(open) => !open && setShowMappingEditor(false)}>
        <DialogContent className="max-w-lg max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{editingMapping ? 'Edit Field Mapping' : 'Create Field Mapping'}</DialogTitle>
            <DialogDescription>
              Define how each paystub field maps to a category. Set &quot;Import&quot; to create transactions, or &quot;Ignore&quot; to store data without creating transactions.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">Template Name</label>
                <Input
                  value={mappingEditorName}
                  onChange={(e) => setMappingEditorName(e.target.value)}
                  placeholder="e.g., My Employer Weekly"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">Employer Name</label>
                <Input
                  value={mappingEditorEmployer}
                  onChange={(e) => setMappingEditorEmployer(e.target.value)}
                  placeholder="e.g., Acme Corp"
                />
              </div>
            </div>

            {/* Add new field */}
            <div>
              <label className="block text-sm font-medium text-foreground mb-1">Add Field</label>
              <div className="flex gap-2">
                <select
                  id="newFieldSection"
                  className="text-xs bg-background border border-border rounded px-2 py-1.5 text-foreground"
                >
                  <option value="earnings">Earnings</option>
                  <option value="taxes">Taxes</option>
                  <option value="before_tax_deductions">Pre-Tax Deductions</option>
                  <option value="after_tax_deductions">Post-Tax Deductions</option>
                </select>
                <Input
                  id="newFieldName"
                  placeholder="Description name"
                  className="flex-1"
                />
                <button
                  onClick={() => {
                    const section = (document.getElementById('newFieldSection') as HTMLSelectElement)?.value;
                    const name = (document.getElementById('newFieldName') as HTMLInputElement)?.value;
                    if (section && name) {
                      setMappingEditorFields((prev) => ({
                        ...prev,
                        [`${section}:${name}`]: { action: 'import', categoryId: null },
                      }));
                      (document.getElementById('newFieldName') as HTMLInputElement).value = '';
                    }
                  }}
                  className="px-3 py-1.5 text-xs font-medium text-primary bg-primary/10 hover:bg-primary/20 rounded-lg transition-colors"
                >
                  Add
                </button>
              </div>
            </div>

            {/* Mapping Fields by Section */}
            {Object.entries(groupedMappingKeys(mappingEditorFields)).map(([section, keys]) => (
              <div key={section}>
                <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">
                  {sectionLabel(`${section}:`)}
                </h3>
                <div className="space-y-1.5">
                  {keys.map((key) => {
                    const field = mappingEditorFields[key];
                    return (
                      <div key={key} className="flex items-center gap-2 p-2 bg-muted/30 rounded-lg">
                        <span className="text-xs text-foreground flex-1 min-w-0 truncate">
                          {descriptionLabel(key)}
                        </span>
                        <select
                          value={field.action}
                          onChange={(e) => {
                            setMappingEditorFields((prev) => ({
                              ...prev,
                              [key]: { ...prev[key], action: e.target.value as 'import' | 'ignore' },
                            }));
                          }}
                          className="text-xs bg-background border border-border rounded px-2 py-1 text-foreground w-20"
                        >
                          <option value="import">Import</option>
                          <option value="ignore">Ignore</option>
                        </select>
                        {field.action === 'import' && (
                          <select
                            value={field.categoryId || ''}
                            onChange={(e) => {
                              setMappingEditorFields((prev) => ({
                                ...prev,
                                [key]: { ...prev[key], categoryId: e.target.value || null },
                              }));
                            }}
                            className="text-xs bg-background border border-border rounded px-2 py-1 text-foreground w-36"
                          >
                            <option value="">No category</option>
                            {categories
                              .filter((c) => c.categoryType !== 'transfer')
                              .sort((a, b) => a.name.localeCompare(b.name))
                              .map((c) => (
                                <option key={c.id} value={c.id}>
                                  {c.name} {c.isIncome ? '(Income)' : ''}
                                </option>
                              ))}
                          </select>
                        )}
                        <button
                          onClick={() => {
                            setMappingEditorFields((prev) => {
                              const next = { ...prev };
                              delete next[key];
                              return next;
                            });
                          }}
                          className="text-xs text-destructive hover:text-destructive/80 px-1"
                        >
                          ✕
                        </button>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}

            {Object.keys(mappingEditorFields).length === 0 && (
              <p className="text-sm text-muted-foreground text-center py-4">
                No fields defined. Import a JSON file first or add fields manually above.
              </p>
            )}
          </div>

          <DialogFooter>
            <button
              onClick={() => setShowMappingEditor(false)}
              className="px-4 py-2 text-sm text-foreground bg-muted hover:bg-accent rounded-lg transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleSaveMapping}
              disabled={mappingSaving || !mappingEditorName}
              className="px-4 py-2 text-sm font-semibold text-primary-foreground bg-primary rounded-lg hover:opacity-90 disabled:opacity-50 transition-all"
            >
              {mappingSaving ? 'Saving...' : editingMapping ? 'Update Mapping' : 'Create Mapping'}
            </button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Auto-Generate Editor Dialog ── */}
      <Dialog open={showAutoGenEditor} onOpenChange={(open) => !open && setShowAutoGenEditor(false)}>
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle>Auto-Generate Settings</DialogTitle>
            <DialogDescription>
              Automatically create paystubs when the next pay date arrives. The most recent actual paystub is used as a template.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium text-foreground">Enabled</label>
              <Switch checked={autoGenEnabled} onCheckedChange={setAutoGenEnabled} />
            </div>

            <div>
              <label className="block text-sm font-medium text-foreground mb-1">Field Mapping</label>
              <select
                value={autoGenMappingId}
                onChange={(e) => setAutoGenMappingId(e.target.value)}
                className="w-full text-sm bg-background border border-border rounded-lg px-3 py-2 text-foreground"
              >
                {mappings.map((m) => (
                  <option key={m.id} value={m.id}>{m.name}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-foreground mb-1">Pay Frequency</label>
              <select
                value={autoGenFrequency}
                onChange={(e) => setAutoGenFrequency(e.target.value)}
                className="w-full text-sm bg-background border border-border rounded-lg px-3 py-2 text-foreground"
              >
                <option value="weekly">Weekly</option>
                <option value="biweekly">Biweekly</option>
                <option value="semimonthly">Semi-monthly</option>
                <option value="monthly">Monthly</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-foreground mb-1">Base Paystub (template)</label>
              <select
                value={autoGenBasePaystubId}
                onChange={(e) => setAutoGenBasePaystubId(e.target.value)}
                className="w-full text-sm bg-background border border-border rounded-lg px-3 py-2 text-foreground"
              >
                <option value="">Most recent</option>
                {paystubs.filter((p) => !p.isAutoGenerated).slice(0, 20).map((p) => (
                  <option key={p.id} value={p.id}>
                    {formatDate(p.checkDate)} — {formatCurrency(p.grossCurrent)} gross
                  </option>
                ))}
              </select>
            </div>
          </div>

          <DialogFooter>
            <button
              onClick={() => setShowAutoGenEditor(false)}
              className="px-4 py-2 text-sm text-foreground bg-muted hover:bg-accent rounded-lg transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleSaveAutoGen}
              disabled={autoGenSaving || !autoGenMappingId}
              className="px-4 py-2 text-sm font-semibold text-primary-foreground bg-primary rounded-lg hover:opacity-90 disabled:opacity-50 transition-all"
            >
              {autoGenSaving ? 'Saving...' : 'Save'}
            </button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Paystub Detail Dialog ── */}
      <Dialog open={!!viewingPaystub} onOpenChange={(open) => !open && setViewingPaystub(null)}>
        <DialogContent className="max-w-lg max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Paystub Details</DialogTitle>
            <DialogDescription>
              {viewingPaystub && (
                <>
                  {formatDate(viewingPaystub.checkDate)}
                  {viewingPaystub.employerName && ` · ${viewingPaystub.employerName}`}
                  {viewingPaystub.isAutoGenerated && ' · Auto-generated'}
                </>
              )}
            </DialogDescription>
          </DialogHeader>

          {viewingPaystub && (
            <div className="space-y-4">
              {/* Summary */}
              <div className="grid grid-cols-2 gap-3">
                <div className="p-3 bg-muted/30 rounded-lg">
                  <div className="text-xs text-muted-foreground">Gross</div>
                  <div className="text-sm font-medium text-foreground blur-number">{formatCurrency(viewingPaystub.grossCurrent)}</div>
                </div>
                <div className="p-3 bg-muted/30 rounded-lg">
                  <div className="text-xs text-muted-foreground">Net</div>
                  <div className="text-sm font-medium text-foreground blur-number">{formatCurrency(viewingPaystub.netCurrent)}</div>
                </div>
                <div className="p-3 bg-muted/30 rounded-lg">
                  <div className="text-xs text-muted-foreground">Taxes</div>
                  <div className="text-sm font-medium text-foreground blur-number">{formatCurrency(viewingPaystub.taxesCurrent)}</div>
                </div>
                <div className="p-3 bg-muted/30 rounded-lg">
                  <div className="text-xs text-muted-foreground">Deductions</div>
                  <div className="text-sm font-medium text-foreground blur-number">{formatCurrency(viewingPaystub.deductionsCurrent)}</div>
                </div>
              </div>

              <div className="text-xs text-muted-foreground">
                Pay Period: {formatDate(viewingPaystub.payPeriodStart)} — {formatDate(viewingPaystub.payPeriodEnd)}
              </div>

              {/* Line Items */}
              {viewingPaystub.lineItems && viewingPaystub.lineItems.length > 0 && (
                <div className="space-y-3">
                  {['earnings', 'taxes', 'before_tax_deductions', 'after_tax_deductions'].map((section) => {
                    const items = viewingPaystub.lineItems.filter((li: any) => li.section === section);
                    if (items.length === 0) return null;
                    return (
                      <div key={section}>
                        <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1">
                          {sectionLabel(`${section}:`)}
                        </h4>
                        <div className="space-y-0.5">
                          {items.map((li: any) => (
                            <div key={li.id} className="flex items-center justify-between py-1 px-2 bg-muted/20 rounded">
                              <div className="flex items-center gap-2 min-w-0">
                                <span className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${
                                  li.mappingAction === 'import' ? 'bg-chart-1' : 'bg-muted-foreground/30'
                                }`} />
                                <span className="text-xs text-foreground truncate">{li.description}</span>
                                {li.mappingAction === 'import' && li.categoryId && (
                                  <span className="text-[10px] text-primary/70 flex-shrink-0">→ {getCategoryName(li.categoryId)}</span>
                                )}
                              </div>
                              <span className="text-xs font-mono text-foreground blur-number flex-shrink-0">
                                {formatCurrency(li.amount)}
                              </span>
                            </div>
                          ))}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          <DialogFooter>
            <button
              onClick={() => setViewingPaystub(null)}
              className="px-4 py-2 text-sm text-foreground bg-muted hover:bg-accent rounded-lg transition-colors"
            >
              Close
            </button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Delete Paystub Confirmation ── */}
      <AlertDialog open={!!deletePaystub} onOpenChange={(open) => !open && setDeletePaystub(null)}>
        <AlertDialogContent className="max-w-sm">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Paystub</AlertDialogTitle>
            <AlertDialogDescription>
              Delete the paystub from {deletePaystub ? formatDate(deletePaystub.checkDate) : ''}?
              This will also remove any transactions created from this paystub.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <button
              onClick={handleDeletePaystub}
              disabled={deleteLoading}
              className="inline-flex h-9 items-center justify-center rounded-lg bg-destructive px-4 py-2 text-sm font-semibold text-destructive-foreground hover:opacity-90 transition-opacity disabled:opacity-50"
            >
              {deleteLoading ? 'Deleting...' : 'Delete'}
            </button>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* ── Delete Mapping Confirmation ── */}
      <AlertDialog open={!!deleteMapping} onOpenChange={(open) => !open && setDeleteMapping(null)}>
        <AlertDialogContent className="max-w-sm">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Mapping</AlertDialogTitle>
            <AlertDialogDescription>
              Delete the field mapping &quot;{deleteMapping?.name}&quot;?
              This will not delete any imported paystubs.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <button
              onClick={handleDeleteMapping}
              disabled={deleteMappingLoading}
              className="inline-flex h-9 items-center justify-center rounded-lg bg-destructive px-4 py-2 text-sm font-semibold text-destructive-foreground hover:opacity-90 transition-opacity disabled:opacity-50"
            >
              {deleteMappingLoading ? 'Deleting...' : 'Delete'}
            </button>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
