import { auth } from 'auth';
import { getDb } from '@/lib/db';
import {
  paystubs,
  paystubLineItems,
  paystubFieldMappings,
  accounts,
  transactions,
} from '@/lib/db/schema';
import { createTransactionsFromLineItems } from '../route';
import { getSessionDEK } from '@/lib/crypto-context';
import {
  updateCategorySpendingSummaries,
  updateCategoryIncomeSummaries,
  updateMonthlyCashFlowSummaries,
} from '@/lib/services/sync';
import {
  parseDate,
  normalizeBackendInput,
  fnv1aDigest64,
  computeTiesOut,
  type PaystubTieOutInput,
} from '@/lib/utils/paystub';
import { eq, and, lt, desc } from 'drizzle-orm';

interface RawPaystub {
  employeeName?: string;
  lmPeopleId?: string;
  payPeriodStart: string;
  payPeriodEnd: string;
  checkDate: string;
  adviceNumber?: string;
  grossCurrent?: number | string;
  grossYTD?: number | string;
  taxesCurrent?: number | string;
  taxesYTD?: number | string;
  deductionsCurrent?: number | string;
  deductionsYTD?: number | string;
  netCurrent?: number | string;
  hoursAndEarnings?: Array<{
    description: string;
    hours?: number | string;
    rate?: number | string;
    amount?: number | string;
    ytdHours?: number | string;
    ytdAmount?: number | string;
  }>;
  taxes?: Array<{
    description: string;
    amount?: number | string;
    ytdAmount?: number | string;
  }>;
  beforeTaxDeductions?: Array<{
    description: string;
    amount?: number | string;
    ytdAmount?: number | string;
  }>;
  afterTaxDeductions?: Array<{
    description: string;
    amount?: number | string;
    ytdAmount?: number | string;
  }>;
}





export async function POST(request: Request) {
  const session = await auth();
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const userId = session.user.id;
  const dataUserId = (session.user as any).dataUserId ?? session.user.id;
  const dek = await getSessionDEK();

  let body: {
    paystubs: any;
    mappingId: string;
    startDate?: string;
    employerName: string;
  };
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: 'Invalid request body' }, { status: 400 });
  }

  const { paystubs: inputPaystubs, mappingId, startDate, employerName } = body;
  const rawPaystubs = normalizeBackendInput(inputPaystubs);

  if (rawPaystubs.length === 0 || !mappingId) {
    return Response.json(
      { error: 'paystubs array and mappingId are required' },
      { status: 400 }
    );
  }

  // Look up the field mapping template
  const [mapping] = await db
    .select()
    .from(paystubFieldMappings)
    .where(
      and(
        eq(paystubFieldMappings.id, mappingId),
        eq(paystubFieldMappings.userId, dataUserId)
      )
    )
    .limit(1);

  if (!mapping) {
    return Response.json({ error: 'Mapping template not found' }, { status: 404 });
  }

  const mappingsJson = (mapping.mappings || {}) as Record<
    string,
    { action: 'import' | 'ignore'; categoryId: string | null }
  >;

  // Load existing user imported paystubs to support YTD continuity tie-out checks and fast deduplication
  const existingImportedPaystubs = await db
    .select({
      id: paystubs.id,
      checkDate: paystubs.checkDate,
      grossCurrent: paystubs.grossCurrent,
      taxesCurrent: paystubs.taxesCurrent,
      deductionsCurrent: paystubs.deductionsCurrent,
      netCurrent: paystubs.netCurrent,
      grossYtd: paystubs.grossYtd,
      taxesYtd: paystubs.taxesYtd,
      deductionsYtd: paystubs.deductionsYtd,
      adviceNumber: paystubs.adviceNumber,
      importKey: paystubs.importKey,
    })
    .from(paystubs)
    .where(and(eq(paystubs.userId, dataUserId), eq(paystubs.isAutoGenerated, false)))
    .orderBy(desc(paystubs.checkDate));

  const knownAdviceNumbers = new Set(
    existingImportedPaystubs.map((p) => p.adviceNumber).filter((v): v is string => Boolean(v))
  );
  const knownImportKeys = new Set(
    existingImportedPaystubs.map((p) => p.importKey).filter((v): v is string => Boolean(v))
  );

  let imported = 0;
  let skipped = 0;
  const total = rawPaystubs.length;

  for (const raw of rawPaystubs) {
    // Parse dates
    const checkDate = parseDate(raw.checkDate);
    const payPeriodStart = parseDate(raw.payPeriodStart);
    const payPeriodEnd = parseDate(raw.payPeriodEnd);

    // Filter by startDate if provided
    if (startDate && checkDate < startDate) {
      skipped++;
      continue;
    }

    // P-4: Stable dedupe check. If adviceNumber is present, check adviceNumber.
    // Otherwise, check fallback hash key (userId, employer, checkDate, gross, taxes).
    const computedImportKey = raw.adviceNumber
      ? null
      : fnv1aDigest64(
          `${dataUserId}:${employerName || ''}:${checkDate}:${raw.grossCurrent ?? '0'}:${raw.taxesCurrent ?? '0'}`
        );

    if (raw.adviceNumber && knownAdviceNumbers.has(raw.adviceNumber)) {
      skipped++;
      continue;
    }
    if (computedImportKey && knownImportKeys.has(computedImportKey)) {
      skipped++;
      continue;
    }

    // P-2: Compute tie-out continuity against prior imported stubs
    const priorStubs = existingImportedPaystubs
      .filter((p) => p.checkDate < checkDate)
      .map((p) => ({
        checkDate: p.checkDate,
        gross: p.grossCurrent,
        taxes: p.taxesCurrent,
        deductions: p.deductionsCurrent,
        net: p.netCurrent,
        grossYtd: p.grossYtd,
        taxesYtd: p.taxesYtd,
        deductionsYtd: p.deductionsYtd,
      }));

    const tiesOut = computeTiesOut(
      {
        checkDate,
        gross: raw.grossCurrent ?? 0,
        taxes: raw.taxesCurrent ?? 0,
        deductions: raw.deductionsCurrent ?? 0,
        net: raw.netCurrent ?? 0,
        grossYtd: raw.grossYTD,
        taxesYtd: raw.taxesYTD,
        deductionsYtd: raw.deductionsYTD,
      },
      priorStubs
    );

    // Insert paystub
    const [paystub] = await db
      .insert(paystubs)
      .values({
        userId: dataUserId,
        employerName: employerName || '',
        employeeName: raw.employeeName || null,
        payPeriodStart,
        payPeriodEnd,
        checkDate,
        adviceNumber: raw.adviceNumber || null,
        grossCurrent: String(raw.grossCurrent ?? '0'),
        taxesCurrent: String(raw.taxesCurrent ?? '0'),
        deductionsCurrent: String(raw.deductionsCurrent ?? '0'),
        netCurrent: String(raw.netCurrent ?? '0'),
        grossYtd: raw.grossYTD != null ? String(raw.grossYTD) : null,
        taxesYtd: raw.taxesYTD != null ? String(raw.taxesYTD) : null,
        deductionsYtd: raw.deductionsYTD != null ? String(raw.deductionsYTD) : null,
        tiesOut,
        importKey: computedImportKey,
        source: 'json',
        mappingId,
        sourceJson: JSON.stringify(raw),
      })
      .returning();

    // Track newly inserted stub for in-batch deduplication & tie-out chaining
    if (raw.adviceNumber) knownAdviceNumbers.add(raw.adviceNumber);
    if (computedImportKey) knownImportKeys.add(computedImportKey);
    existingImportedPaystubs.push({
      id: paystub.id,
      checkDate: paystub.checkDate,
      grossCurrent: paystub.grossCurrent,
      taxesCurrent: paystub.taxesCurrent,
      deductionsCurrent: paystub.deductionsCurrent,
      netCurrent: paystub.netCurrent,
      grossYtd: paystub.grossYtd,
      taxesYtd: paystub.taxesYtd,
      deductionsYtd: paystub.deductionsYtd,
      adviceNumber: paystub.adviceNumber,
      importKey: paystub.importKey,
    });
    existingImportedPaystubs.sort((a, b) => b.checkDate.localeCompare(a.checkDate));

    // Build and insert line items
    const allLineItems: Array<{
      id: string;
      section: string;
      description: string;
      amount: string;
      mappingAction: string;
      categoryId: string | null;
    }> = [];

    // Helper to insert line items for a section
    async function insertSectionItems(
      items: Array<any> | undefined,
      section: string,
      includeHours: boolean
    ) {
      if (!items || !Array.isArray(items)) return;
      for (const item of items) {
        const descKey = item.description || '';
        const lookupKey = `${section}:${descKey}`;
        const mappingEntry = mappingsJson[lookupKey];
        const mappingAction = mappingEntry?.action || 'import';
        const categoryId = mappingEntry?.categoryId || null;

        const [inserted] = await db
          .insert(paystubLineItems)
          .values({
            paystubId: paystub.id,
            userId: dataUserId,
            section,
            description: descKey,
            amount: String(item.amount ?? '0'),
            ytdAmount: item.ytdAmount != null ? String(item.ytdAmount) : null,
            hours: includeHours && item.hours != null ? String(item.hours) : null,
            rate: includeHours && item.rate != null ? String(item.rate) : null,
            ytdHours:
              includeHours && item.ytdHours != null ? String(item.ytdHours) : null,
            mappingAction,
            categoryId,
          })
          .returning();

        allLineItems.push(inserted);
      }
    }

    await insertSectionItems(raw.hoursAndEarnings, 'earnings', true);
    await insertSectionItems(raw.taxes, 'taxes', false);
    await insertSectionItems(raw.beforeTaxDeductions, 'before_tax_deductions', false);
    await insertSectionItems(raw.afterTaxDeductions, 'after_tax_deductions', false);

    // Create transactions from mapped line items
    await createTransactionsFromLineItems(
      db,
      dataUserId,
      paystub,
      allLineItems,
      employerName,
      checkDate,
      dek
    );

    imported++;
  }

  // Recalculate summaries to update charts
  await updateCategorySpendingSummaries(dataUserId, dek);
  await updateCategoryIncomeSummaries(dataUserId, dek);
  await updateMonthlyCashFlowSummaries(dataUserId, dek);

  return Response.json({ imported, skipped, total });
}
