import { auth } from 'auth';
import { getDb } from '@/lib/db';
import { paystubs, paystubLineItems, transactions, accounts } from '@/lib/db/schema';
import { eq, and, desc } from 'drizzle-orm';

export async function GET(request: Request) {
  const session = await auth();
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const userId = session.user.id;
  const { searchParams } = new URL(request.url);

  const limit = searchParams.get('limit') ? parseInt(searchParams.get('limit')!, 10) : undefined;
  const offset = searchParams.get('offset') ? parseInt(searchParams.get('offset')!, 10) : undefined;
  const autoGenerated = searchParams.get('autoGenerated');

  const conditions = [eq(paystubs.userId, userId)];
  if (autoGenerated === 'true') {
    conditions.push(eq(paystubs.isAutoGenerated, true));
  } else if (autoGenerated === 'false') {
    conditions.push(eq(paystubs.isAutoGenerated, false));
  }

  let query = db
    .select()
    .from(paystubs)
    .where(and(...conditions))
    .orderBy(desc(paystubs.checkDate))
    .$dynamic();

  if (limit !== undefined) {
    query = query.limit(limit);
  }
  if (offset !== undefined) {
    query = query.offset(offset);
  }

  const result = await query;
  return Response.json(result);
}

export async function POST(request: Request) {
  const session = await auth();
  if (!session?.user?.id) {
    return Response.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const db = getDb();
  const userId = session.user.id;

  let body: Record<string, any>;
  try {
    body = await request.json();
  } catch {
    return Response.json({ error: 'Invalid request body' }, { status: 400 });
  }

  const {
    employerName,
    employeeName,
    payPeriodStart,
    payPeriodEnd,
    checkDate,
    adviceNumber,
    grossCurrent,
    taxesCurrent,
    deductionsCurrent,
    netCurrent,
    grossYtd,
    taxesYtd,
    deductionsYtd,
    lineItems,
  } = body;

  // Insert the paystub
  const [paystub] = await db
    .insert(paystubs)
    .values({
      userId,
      employerName: employerName || '',
      employeeName: employeeName || null,
      payPeriodStart,
      payPeriodEnd,
      checkDate,
      adviceNumber: adviceNumber || null,
      grossCurrent: String(grossCurrent ?? '0'),
      taxesCurrent: String(taxesCurrent ?? '0'),
      deductionsCurrent: String(deductionsCurrent ?? '0'),
      netCurrent: String(netCurrent ?? '0'),
      grossYtd: grossYtd != null ? String(grossYtd) : null,
      taxesYtd: taxesYtd != null ? String(taxesYtd) : null,
      deductionsYtd: deductionsYtd != null ? String(deductionsYtd) : null,
      source: 'manual',
    })
    .returning();

  // Insert line items
  const insertedLineItems = [];
  if (Array.isArray(lineItems) && lineItems.length > 0) {
    for (const item of lineItems) {
      const [inserted] = await db
        .insert(paystubLineItems)
        .values({
          paystubId: paystub.id,
          userId,
          section: item.section,
          description: item.description,
          amount: String(item.amount ?? '0'),
          ytdAmount: item.ytdAmount != null ? String(item.ytdAmount) : null,
          hours: item.hours != null ? String(item.hours) : null,
          rate: item.rate != null ? String(item.rate) : null,
          ytdHours: item.ytdHours != null ? String(item.ytdHours) : null,
          mappingAction: item.mappingAction || 'import',
          categoryId: item.categoryId || null,
        })
        .returning();
      insertedLineItems.push(inserted);
    }
  }

  // Create transactions from mapped line items
  await createTransactionsFromLineItems(
    db,
    userId,
    paystub,
    insertedLineItems,
    employerName,
    checkDate
  );

  // Re-fetch line items to include any transactionId updates
  const finalLineItems = await db
    .select()
    .from(paystubLineItems)
    .where(eq(paystubLineItems.paystubId, paystub.id));

  return Response.json({ ...paystub, lineItems: finalLineItems }, { status: 201 });
}

/**
 * Create transactions from paystub line items.
 * Shared logic used by manual POST, import, and auto-generate.
 */
export async function createTransactionsFromLineItems(
  db: ReturnType<typeof getDb>,
  userId: string,
  paystub: { id: string; checkDate: string },
  lineItems: Array<{
    id: string;
    section: string;
    description: string;
    amount: string;
    mappingAction: string;
    categoryId: string | null;
  }>,
  employerName: string,
  checkDate: string
) {
  // Find any account belonging to this user
  const [userAccount] = await db
    .select()
    .from(accounts)
    .where(eq(accounts.userId, userId))
    .limit(1);

  if (!userAccount) {
    return; // No account found, skip transaction creation
  }

  const mappedItems = lineItems.filter(
    (item) => item.mappingAction === 'import' && item.categoryId
  );

  if (mappedItems.length === 0) return;

  // EARNINGS: Create a single transaction for gross amount
  const earningsItems = mappedItems.filter((item) => item.section === 'earnings');
  if (earningsItems.length > 0) {
    // Compute total earnings from mapped line items
    const totalEarnings = earningsItems.reduce(
      (sum, item) => sum + parseFloat(item.amount || '0'),
      0
    );
    const firstEarningsCategoryId = earningsItems[0].categoryId;
    const earningsExternalId = `paystub-${paystub.id}-${earningsItems[0].id}`;

    const [txn] = await db
      .insert(transactions)
      .values({
        userId,
        accountId: userAccount.id,
        externalId: earningsExternalId,
        date: checkDate,
        amount: String(totalEarnings),
        description: `Paycheck - ${employerName}`,
        source: 'paystub',
        paystubId: paystub.id,
        categoryId: firstEarningsCategoryId,
        reviewed: true,
      })
      .returning();

    // Link all earnings line items to this transaction
    for (const item of earningsItems) {
      await db
        .update(paystubLineItems)
        .set({ transactionId: txn.id })
        .where(eq(paystubLineItems.id, item.id));
    }
  }

  // TAXES and DEDUCTIONS: Create individual transactions
  const expenseItems = mappedItems.filter(
    (item) =>
      item.section === 'taxes' ||
      item.section === 'before_tax_deductions' ||
      item.section === 'after_tax_deductions'
  );

  for (const item of expenseItems) {
    const amount = parseFloat(item.amount || '0');
    const negativeAmount = -Math.abs(amount);
    const externalId = `paystub-${paystub.id}-${item.id}`;

    const [txn] = await db
      .insert(transactions)
      .values({
        userId,
        accountId: userAccount.id,
        externalId,
        date: checkDate,
        amount: String(negativeAmount),
        description: item.description,
        source: 'paystub',
        paystubId: paystub.id,
        categoryId: item.categoryId,
        reviewed: true,
      })
      .returning();

    await db
      .update(paystubLineItems)
      .set({ transactionId: txn.id })
      .where(eq(paystubLineItems.id, item.id));
  }
}
