import {
  boolean,
  date,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';
import { accounts } from './accounts';
import { categories, transactions, tags } from './transactions';

// ── Paystubs ─────────────────────────────────────────────────────────────────
export const paystubs = pgTable('paystubs', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull(),
  employerName: text('employer_name').notNull().default(''),
  employeeName: text('employee_name'),
  payPeriodStart: date('pay_period_start').notNull(),
  payPeriodEnd: date('pay_period_end').notNull(),
  checkDate: date('check_date').notNull(),
  adviceNumber: text('advice_number'),
  grossCurrent: text('gross_current').notNull().default('0'),
  taxesCurrent: text('taxes_current').notNull().default('0'),
  deductionsCurrent: text('deductions_current').notNull().default('0'),
  netCurrent: text('net_current').notNull().default('0'),
  grossYtd: text('gross_ytd'),
  taxesYtd: text('taxes_ytd'),
  deductionsYtd: text('deductions_ytd'),
  source: text('source').notNull().default('manual'), // 'json' | 'manual' | 'auto_generated'
  isAutoGenerated: boolean('is_auto_generated').notNull().default(false),
  mappingId: uuid('mapping_id'),
  sourceJson: text('source_json'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Paystub Line Items ───────────────────────────────────────────────────────
export const paystubLineItems = pgTable('paystub_line_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  paystubId: uuid('paystub_id').notNull().references(() => paystubs.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull(),
  section: text('section').notNull(), // 'earnings' | 'taxes' | 'before_tax_deductions' | 'after_tax_deductions'
  description: text('description').notNull(),
  amount: text('amount').notNull().default('0'),
  ytdAmount: text('ytd_amount'),
  hours: text('hours'),
  rate: text('rate'),
  ytdHours: text('ytd_hours'),
  mappingAction: text('mapping_action').notNull().default('import'), // 'import' | 'ignore'
  categoryId: uuid('category_id').references(() => categories.id, { onDelete: 'set null' }),
  transactionId: uuid('transaction_id').references(() => transactions.id, { onDelete: 'set null' }),
});

// ── Paystub Field Mappings ───────────────────────────────────────────────────
// Reusable templates that define how paystub line items map to categories
export const paystubFieldMappings = pgTable('paystub_field_mappings', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull(),
  name: text('name').notNull(),
  employerName: text('employer_name').notNull().default(''),
  isDefault: boolean('is_default').notNull().default(false),
  mappings: jsonb('mappings').notNull().default({}),
  accountId: uuid('account_id').references(() => accounts.id, { onDelete: 'set null' }),
  tagId: uuid('tag_id').references(() => tags.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// ── Paystub Auto-Generate Settings ───────────────────────────────────────────
// Controls automatic creation of paystubs at the user-defined pay frequency
export const paystubAutoGenerateSettings = pgTable(
  'paystub_auto_generate_settings',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: text('user_id').notNull(),
    mappingId: uuid('mapping_id').notNull().references(() => paystubFieldMappings.id, { onDelete: 'cascade' }),
    isEnabled: boolean('is_enabled').notNull().default(false),
    frequency: text('frequency').notNull().default('weekly'), // 'weekly' | 'biweekly' | 'semimonthly' | 'monthly'
    basePaystubId: uuid('base_paystub_id').references(() => paystubs.id, { onDelete: 'set null' }),
    lastGeneratedDate: date('last_generated_date'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [unique().on(t.userId, t.mappingId)]
);
