import { describe, it, expect } from 'vitest';
import {
  addFrequencyInterval,
  getFrequencyDays,
  parseDate,
  normalizeBackendInput,
  isOasdiLine,
  isSection125Line,
  computeOasdiYtdBefore,
  capOasdiAmount,
  computeTiesOut,
  fnv1aDigest64,
  nextCadenceDate,
} from '@/lib/utils/paystub';

describe('nextCadenceDate (S-1 semimonthly anchoring)', () => {
  it('steps on {1, 15} when the anchor day is in the first half of the month', () => {
    expect(nextCadenceDate('2026-07-03', 'semimonthly')).toBe('2026-07-15');
    // Day-15 anchors keep the {1, 15} pattern → the next anchor is the 1st.
    expect(nextCadenceDate('2026-07-15', 'semimonthly')).toBe('2026-08-01');
    expect(nextCadenceDate('2026-07-29', 'semimonthly')).toBe('2026-07-31');
    expect(nextCadenceDate('2026-07-31', 'semimonthly')).toBe('2026-08-15');
  });

  it('keeps dates on real calendar pay days and never drifts (12-month walk)', () => {
    // The old +15-day walk from 07-03 would drift to 07-18, 08-02, …
    let d = '2026-07-03';
    const dates: string[] = [];
    for (let i = 0; i < 25; i++) {
      d = nextCadenceDate(d, 'semimonthly');
      dates.push(d);
      expect(d).toMatch(/^(\d{4})-(\d{2})-(01|15|28|29|30|31)$/);
      // Day must be 1, 15, or month-end (Feb EOM = 28/29).
      const day = Number(d.slice(8));
      const eomDay = new Date(
        Date.UTC(Number(d.slice(0, 4)), Number(d.slice(5, 7)), 0)
      ).getUTCDate();
      expect([1, 15, eomDay]).toContain(day);
    }
    expect(dates[0]).toBe('2026-07-15');
    expect(dates[2]).toBe('2026-08-15');
    // Exactly one year later, still on the 15th — zero drift.
    expect(dates[dates.length - 1]).toBe('2027-07-15');
  });

  it('steps on {15, EOM} when the anchor day is in the second half', () => {
    expect(nextCadenceDate('2026-07-17', 'semimonthly')).toBe('2026-07-31');
    expect(nextCadenceDate('2026-06-30', 'semimonthly')).toBe('2026-07-15');
  });

  it('handles the year boundary', () => {
    expect(nextCadenceDate('2026-12-31', 'semimonthly')).toBe('2027-01-15');
    expect(nextCadenceDate('2026-12-01', 'semimonthly')).toBe('2026-12-15');
  });

  it('uses fixed intervals for non-semimonthly frequencies', () => {
    expect(nextCadenceDate('2026-05-29', 'biweekly')).toBe('2026-06-12');
    expect(nextCadenceDate('2026-05-29', 'weekly')).toBe('2026-06-05');
    expect(nextCadenceDate('2026-05-29', 'monthly')).toBe('2026-06-29');
  });
});

describe('S-3 template resolution (imported stubs only)', () => {
  // `findMostRecentImportedBefore` is module-private; exercise the rule
  // through the exported nextCadenceDate? No — the template rule lives in
  // runAutoGenerate. The pure logic is: template = last non-auto stub
  // before the date.
  const imported = (day: string) => ({ id: `imp-${day}`, checkDate: day, isAutoGenerated: false });
  const auto = (day: string) => ({ id: `auto-${day}`, checkDate: day, isAutoGenerated: true });

  const mostRecentImportedBefore = (list: any[], date: string) => {
    const past = list.filter((p) => p.checkDate < date && !p.isAutoGenerated);
    if (past.length === 0) return null;
    return past[past.length - 1];
  };

  it('skips auto-generated bonus stubs when choosing a template', () => {
    const list = [
      imported('2026-06-05'),
      auto('2026-06-19'),
      auto('2026-07-03'),
      auto('2026-07-17'), // ← bonus stub, must NOT be the template
    ];
    const template = mostRecentImportedBefore(list, '2026-07-31');
    expect(template?.id).toBe('imp-2026-06-05');
  });

  it('falls back to null when nothing has been imported yet', () => {
    const list = [auto('2026-07-17')];
    expect(mostRecentImportedBefore(list, '2026-07-31')).toBeNull();
  });
});

describe('Paystubs Helpers', () => {
  describe('parseDate', () => {
    it('parses MM/DD/YYYY dates to YYYY-MM-DD', () => {
      expect(parseDate('05/29/2026')).toBe('2026-05-29');
      expect(parseDate('12/01/2022')).toBe('2022-12-01');
      expect(parseDate('01/05/2024')).toBe('2024-01-05');
    });

    it('returns original string if not in MM/DD/YYYY format', () => {
      expect(parseDate('2026-05-29')).toBe('2026-05-29');
      expect(parseDate('invalid-date')).toBe('invalid-date');
    });
  });

  describe('addFrequencyInterval', () => {
    it('handles weekly frequency (+7 days)', () => {
      expect(addFrequencyInterval('2026-05-29', 'weekly')).toBe('2026-06-05');
      expect(addFrequencyInterval('2026-12-28', 'weekly')).toBe('2027-01-04');
    });

    it('handles biweekly frequency (+14 days)', () => {
      expect(addFrequencyInterval('2026-05-29', 'biweekly')).toBe('2026-06-12');
      expect(addFrequencyInterval('2026-12-20', 'biweekly')).toBe('2027-01-03');
    });

    it('handles semimonthly frequency (+15 days)', () => {
      expect(addFrequencyInterval('2026-05-29', 'semimonthly')).toBe('2026-06-13');
      expect(addFrequencyInterval('2026-12-20', 'semimonthly')).toBe('2027-01-04');
    });

    it('handles monthly frequency (+1 month)', () => {
      expect(addFrequencyInterval('2026-05-29', 'monthly')).toBe('2026-06-29');
      expect(addFrequencyInterval('2026-12-29', 'monthly')).toBe('2027-01-29');
      // Leap year check: Feb 2024 has 29 days
      expect(addFrequencyInterval('2024-01-31', 'monthly')).toBe('2024-02-29');
    });

    it('defaults to biweekly for unknown frequency', () => {
      expect(addFrequencyInterval('2026-05-29', 'unknown')).toBe('2026-06-12');
    });
  });

  describe('getFrequencyDays', () => {
    it('returns correct days for each frequency', () => {
      expect(getFrequencyDays('weekly')).toBe(7);
      expect(getFrequencyDays('biweekly')).toBe(14);
      expect(getFrequencyDays('semimonthly')).toBe(15);
      expect(getFrequencyDays('monthly')).toBe(30);
      expect(getFrequencyDays('unknown')).toBe(14);
    });
  });

  describe('normalizeBackendInput', () => {
    const alternativeFormat = {
      employee: {
        name: "Alice Smith",
        bemsid: "987654",
        company: "Boeing"
      },
      paychecks: [
        {
          checkNumber: "CHK12345",
          checkDate: "05/29/2026",
          totals: {
            earningsHours: 80,
            earningsAmount: 4000.00,
            deductionsAmount: 500.00,
            taxesAmount: 800.00
          },
          earnings: [
            {
              description: "Regular Pay",
              hours: 80,
              amount: 4000.00,
              payPeriodEndDate: "05/28/2026",
              beginDate: "05/15/2026",
              endDate: "05/28/2026"
            }
          ],
          deductions: [
            {
              description: "Savings-SSP/401k",
              amount: 400.00
            },
            {
              description: "Medical",
              amount: 100.00
            }
          ],
          taxes: [
            {
              description: "Fed Withholding",
              amount: 600.00
            },
            {
              description: "OASDI/SS",
              amount: 200.00
            }
          ]
        }
      ]
    };

    it('normalizes alternative paychecks format directly', () => {
      const normalized = normalizeBackendInput(alternativeFormat);
      expect(normalized.length).toBe(1);
      expect(normalized[0]).toEqual({
        employeeName: "Alice Smith",
        payPeriodStart: "05/15/2026",
        payPeriodEnd: "05/28/2026",
        checkDate: "05/29/2026",
        adviceNumber: "CHK12345",
        grossCurrent: "4000",
        taxesCurrent: "800",
        deductionsCurrent: "500",
        netCurrent: "2700",
        hoursAndEarnings: [
          { description: "Regular Pay", hours: 80, amount: 4000 }
        ],
        taxes: [
          { description: "Fed Withholding", amount: 600 },
          { description: "OASDI/SS", amount: 200 }
        ],
        beforeTaxDeductions: [
          { description: "Savings-SSP/401k", amount: 400 },
          { description: "Medical", amount: 100 }
        ],
        afterTaxDeductions: []
      });
    });

    it('normalizes alternative paychecks format when wrapped in an array', () => {
      const normalized = normalizeBackendInput([alternativeFormat]);
      expect(normalized.length).toBe(1);
      expect(normalized[0].employeeName).toBe("Alice Smith");
    });

    it('passes through already standard format arrays unchanged', () => {
      const standardFormat = [
        {
          employeeName: "John Doe",
          payPeriodStart: "05/15/2026",
          payPeriodEnd: "05/28/2026",
          checkDate: "05/29/2026",
          grossCurrent: "3721.15"
        }
      ];
      const normalized = normalizeBackendInput(standardFormat);
      expect(normalized).toBe(standardFormat);
    });

    it('returns empty array for invalid/empty inputs', () => {
      expect(normalizeBackendInput(null)).toEqual([]);
      expect(normalizeBackendInput(undefined)).toEqual([]);
      expect(normalizeBackendInput({})).toEqual([]);
    });

    it('preserves explicit afterTaxDeductions from the payload (P-5)', () => {
      const payload = {
        employee: { name: 'Alice' },
        paychecks: [
          {
            checkDate: '05/29/2026',
            totals: { earningsAmount: 4000, taxesAmount: 800, deductionsAmount: 700 },
            earnings: [{ description: 'Regular Pay', hours: 80, amount: 4000 }],
            taxes: [{ description: 'Fed Withholding', amount: 500, ytdAmount: 2500 }],
            deductions: [{ description: '401k Pre-Tax', amount: 400, ytdAmount: 1600 }],
            afterTaxDeductions: [{ description: 'Roth 401k', amount: 300, ytdAmount: 1200 }],
          },
        ],
      };
      const normalized = normalizeBackendInput(payload);
      expect(normalized[0].afterTaxDeductions).toEqual([
        { description: 'Roth 401k', amount: 300, ytdAmount: 1200 },
      ]);
      expect(normalized[0].taxes).toEqual([
        { description: 'Fed Withholding', amount: 500, ytdAmount: 2500 },
      ]);
      expect(normalized[0].beforeTaxDeductions).toEqual([
        { description: '401k Pre-Tax', amount: 400, ytdAmount: 1600 },
      ]);
    });
  });

  describe('OASDI wage-base cap (P-1)', () => {
    const WAGE_BASE_2026 = 184500;
    const RATE = 0.062;

    it('detects OASDI lines by common payroll labels, tax or pre-tax section', () => {
      expect(isOasdiLine('taxes', 'OASDI/SS')).toBe(true);
      expect(isOasdiLine('taxes', 'Social Security')).toBe(true);
      expect(isOasdiLine('taxes', 'SS')).toBe(true);
      expect(isOasdiLine('before_tax_deductions', 'Social Security Tax')).toBe(true);
      expect(isOasdiLine('earnings', 'Social Security Bonus')).toBe(false);
      expect(isOasdiLine('taxes', 'SSNUI Bonus')).toBe(false);
      expect(isOasdiLine('after_tax_deductions', 'OASDI')).toBe(false);
    });

    it('accrued YTD wages/OASDI across a year never exceed the statutory base', () => {
      // 23 biweekly stubs at $8,000 gross with $496 OASDI each (6.2% of 8,000)
      // → YTD wages $184,000, $500 below the $184,500 2026 base.
      const paystubsList = [];
      const lineItems = new Map<string, any[]>();
      for (let i = 0; i < 23; i++) {
        const id = `p${i}`;
        const date = `2026-${String(Math.min(12, Math.floor(i / 2) + 1)).padStart(2, '0')}-${String((i % 2) * 14 + 15).padStart(2, '0')}`;
        paystubsList.push({ id, checkDate: date, grossCurrent: '8000.00' });
        lineItems.set(id, [{ section: 'taxes', description: 'Social Security', amount: '496.00' }]);
      }
      // State before a hypothetical 24th stub:
      const ytd = computeOasdiYtdBefore(paystubsList, lineItems, '2026-12-30');
      expect(ytd.wagesBefore).toBe(23 * 8000);
      expect(ytd.oasdiBefore).toBe(23 * 496);

      // The 24th $8,000 stub only has $500 of wages left inside the base
      // → OASDI is capped at $500 × 6.2%.
      const cappedBefore24th = capOasdiAmount({
        expectedOasdi: 496,
        gross: 8000,
        ytd,
        wageBaseCap: WAGE_BASE_2026,
        oasdiRate: RATE,
      });
      expect(cappedBefore24th).toBeCloseTo(500 * RATE, 5);

      // After 24 stubs the base is fully exhausted → OASDI rolls off to zero.
      const exhaustedYtd: any = { wagesBefore: 192000, oasdiBefore: 13056, taxYear: 2026 };
      expect(
        capOasdiAmount({ expectedOasdi: 496, gross: 8000, ytd: exhaustedYtd, wageBaseCap: WAGE_BASE_2026, oasdiRate: RATE }),
      ).toBe(0);
    });

    it('partially caps the stub that crosses the base boundary', () => {
      // YTD wages 180,000; next stub earns 8,000 → only 4,500 is taxable.
      const ytd = { wagesBefore: 180000, oasdiBefore: 180000 * RATE, taxYear: 2026 };
      const capped = capOasdiAmount({
        expectedOasdi: 496,
        gross: 8000,
        ytd,
        wageBaseCap: WAGE_BASE_2026,
        oasdiRate: RATE,
      });
      expect(capped).toBeCloseTo(4500 * RATE, 5); // $279
      expect(capped).toBeLessThan(496);
    });

    it('detects IRC §125 Cafeteria / POP pre-tax lines that reduce FICA wages', () => {
      expect(isSection125Line('before_tax_deductions', 'Medical Premium')).toBe(true);
      expect(isSection125Line('before_tax_deductions', 'Dental PPO')).toBe(true);
      expect(isSection125Line('before_tax_deductions', 'Vision Basic')).toBe(true);
      expect(isSection125Line('before_tax_deductions', 'HSA Contribution')).toBe(true);
      expect(isSection125Line('before_tax_deductions', 'Health FSA')).toBe(true);
      expect(isSection125Line('before_tax_deductions', 'DCFSA Dependent Care')).toBe(true);
      expect(isSection125Line('before_tax_deductions', 'Section 125 POP')).toBe(true);

      // Non-Section 125 lines must NOT match
      expect(isSection125Line('before_tax_deductions', '401k Pre-Tax')).toBe(false);
      expect(isSection125Line('before_tax_deductions', '403b Contribution')).toBe(false);
      expect(isSection125Line('after_tax_deductions', 'Roth 401k')).toBe(false);
      expect(isSection125Line('taxes', 'Federal Income Tax')).toBe(false);
      expect(isSection125Line('earnings', 'Medical Allowance')).toBe(false);
    });

    it('subtracts Section 125 deductions to track true FICA-taxable wages for OASDI cap (F04-2)', () => {
      // Worker earns $8,000 gross per bi-weekly paycheck, with $1,000 in Section 125 medical/HSA deductions.
      // True FICA taxable wages per check = $7,000.
      const paystubsList = [];
      const lineItems = new Map<string, any[]>();
      for (let i = 0; i < 23; i++) {
        const id = `p${i}`;
        const date = `2026-${String(Math.min(12, Math.floor(i / 2) + 1)).padStart(2, '0')}-${String((i % 2) * 14 + 15).padStart(2, '0')}`;
        paystubsList.push({ id, checkDate: date, grossCurrent: '8000.00' });
        lineItems.set(id, [
          { section: 'before_tax_deductions', description: 'Medical Insurance', amount: '600.00' },
          { section: 'before_tax_deductions', description: 'HSA Contribution', amount: '400.00' },
          { section: 'before_tax_deductions', description: '401k Retirement', amount: '800.00' }, // Not Sec 125!
          { section: 'taxes', description: 'Social Security', amount: '434.00' }, // 6.2% of 7000
        ]);
      }

      const ytd = computeOasdiYtdBefore(paystubsList, lineItems, '2026-12-30');
      // FICA wages before: 23 * (8000 - 1000) = 161,000 (NOT 23 * 8000 = 184,000!)
      expect(ytd.wagesBefore).toBe(23 * 7000);
      expect(ytd.oasdiBefore).toBeCloseTo(23 * 434, 2);

      // On the 24th stub ($8,000 gross, $1,000 Sec 125 = $7,000 FICA wage):
      // Remaining wage base = $184,500 - $161,000 = $23,500 > $7,000.
      // Full expected OASDI ($434) is withheld, not capped prematurely!
      const capped24th = capOasdiAmount({
        expectedOasdi: 434,
        gross: 8000,
        section125Deductions: 1000,
        ytd,
        wageBaseCap: WAGE_BASE_2026,
        oasdiRate: RATE,
      });
      expect(capped24th).toBe(434);
    });

    it('computes tie-out continuity and fnv1a deduplication hashes (F04-4)', () => {
      const hash1 = fnv1aDigest64('user_1:Employer A:2026-06-15:5000:1000');
      const hash2 = fnv1aDigest64('user_1:Employer A:2026-06-15:5000:1000');
      const hash3 = fnv1aDigest64('user_1:Employer A:2026-06-30:5000:1000');

      expect(hash1).toBe(hash2);
      expect(hash1).not.toBe(hash3);
      expect(typeof hash1).toBe('string');
      expect(hash1.length).toBe(16);

      // Tie-out: Paycheck 1 (January 15)
      const stub1 = {
        checkDate: '2026-01-15',
        gross: 5000,
        taxes: 1000,
        deductions: 500,
        net: 3500,
        grossYtd: 5000,
        taxesYtd: 1000,
        deductionsYtd: 500,
      };
      expect(computeTiesOut(stub1, [])).toBe(true);

      // Paycheck 2 (January 31) with matching YTD progression
      const stub2 = {
        checkDate: '2026-01-31',
        gross: 5000,
        taxes: 1000,
        deductions: 500,
        net: 3500,
        grossYtd: 10000,
        taxesYtd: 2000,
        deductionsYtd: 1000,
      };
      expect(computeTiesOut(stub2, [stub1])).toBe(true);

      // Paycheck 2 with broken YTD progression
      const brokenStub2 = {
        checkDate: '2026-01-31',
        gross: 5000,
        taxes: 1000,
        deductions: 500,
        net: 3500,
        grossYtd: 12000, // Broken YTD!
        taxesYtd: 2000,
        deductionsYtd: 1000,
      };
      expect(computeTiesOut(brokenStub2, [stub1])).toBe(false);
    });
  });
});
